# Agenda

1. Joins
2. Strings

# Joins

The basic idea behind joining is that you have two different data frames that share an index -- or that share values in an index -- and you want to combine these into a single data frame.

This is very common if you have a large data set that is broken up into multiple files. Typically, each file (i.e., data frame) will have a number of different columns. So a company might have one data set with employee names and personal information, and another one with salary information, and yet another with performance information. If we want to do some analysis that uses information from all three of these data sets, then we'll need (want) to combine them into a single Pandas data frame, and then we can perform our query.

Joining would mean that all three of these data frames share an index, or at least share an index's values. You join across the index(es), get a single, large (wide) data frame, and then perform your queries.

If you don't want to join on the index, but want to use a non-index column, then you can use what Pandas calls "merge." Merging is basically the same as joining, except that it can be done on any column.

You'll often find that you'll need to use `set_index` to move a column into the index (if you want to `join`), or `reset_index` to move a column *out* of the index (if you want to `merge`).

In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [6]:
oil_prices = DataFrame([[1, 60],
                        [2, 65],
                        [3, 63],
                        [4, 69],
                        [5, 72],
                        [6, 65],
                        [7, 60],
                        [8, 55],
                        [9, 60],
                        [10, 62],
                        [11, 63],
                        [12, 65]],
                      columns=['month', 'price'])
oil_prices

    month  price
0       1     60
1       2     65
2       3     63
3       4     69
4       5     72
5       6     65
6       7     60
7       8     55
8       9     60
9      10     62
10     11     63
11     12     65

In [7]:
# I want to know the (mean) price of oil, for each month... that is already in my oil_prices data frame, right?
# Except that I want to see the names of the months, not the numbers.

months = DataFrame([[1, 'January'],
                     [2, 'February'],
                     [3, 'March'],
                     [4, 'April'],
                     [5, 'May'],
                     [6, 'June'],
                     [7, 'July'],
                     [8, 'August'],
                     [9, 'September'],
                     [10, 'October'],
                    [11, 'November'],
                     [12, 'December']],
                  columns=['number', 'name'])

months

    number       name
0        1    January
1        2   February
2        3      March
3        4      April
4        5        May
5        6       June
6        7       July
7        8     August
8        9  September
9       10    October
10      11   November
11      12   December

In [8]:
oil_prices = oil_prices.set_index('month')
months = months.set_index('number')

In [9]:
oil_prices

       price
month
1         60
2         65
3         63
4         69
5         72
6         65
7         60
8         55
9         60
10        62
11        63
12        65

In [10]:
months

             name
number
1         January
2        February
3           March
4           April
5             May
6            June
7            July
8          August
9       September
10        October
11       November
12       December

In [11]:
# in this join,

# oil_prices is known as the "left side"
# and months is known as the "right side"

oil_prices.join(months)

       price       name
month
1         60    January
2         65   February
3         63      March
4         69      April
5         72        May
6         65       June
7         60       July
8         55     August
9         60  September
10        62    October
11        63   November
12        65   December