# Agenda

1. Grouping
2. Pivot tables

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('taxi.csv')

In [9]:
# What is the mean `trip_distance` for 1-passenger rides?

(
    df
    .loc[ pd.col('passenger_count')  == 1 ,   # row selector
        'trip_distance']                      # column selector
    .mean()
)

np.float64(3.0923380047176354)

In [10]:
# What is the mean `trip_distance` for 2-passenger rides?

(
    df
    .loc[ pd.col('passenger_count')  == 2 ,   # row selector
        'trip_distance']                      # column selector
    .mean()
)

np.float64(3.3843869002284848)

In [11]:
# What is the mean `trip_distance` for 3-passenger rides?

(
    df
    .loc[ pd.col('passenger_count')  == 3 ,   # row selector
        'trip_distance']                      # column selector
    .mean()
)

np.float64(3.3423891625615765)

# This is grouping

The idea behind grouping is that:

- We want to run an analysis (typically, an aggregation method)
- On one column
- For each distinct value of a categorical column

The syntax is as follows:

- `df.groupby`
- In the `()`, we'll name the categorical -- this is a column name, and there should be relatively few values in this column
- After that, we'll use `[]` to name the data column on which we'll be calculating
- After that, we invoke an aggregation method

In [12]:
#             categorical       data column      aggregation method
df.groupby('passenger_count')['trip_distance'].mean()

passenger_count
0    4.600000
1    3.092338
2    3.384387
3    3.342389
4    3.628901
5    3.182712
6    3.170976
Name: trip_distance, dtype: float64

The returned series has a standard format:

- The index contains the distinct values from our categorical
- The values of the series are the result of invoking our aggregation method on the data column, filtered so that each categorical value gets a turn

In [13]:
# I could be dumb about this, if I want!

# for every distinct total_amount,
# calculate the mean trip_distance

df.groupby('total_amount')['trip_distance'].mean()

total_amount
-7.80       0.89
-7.30       0.93
-3.30       0.00
 0.30       0.50
 2.30       0.00
           ...
 162.39    32.10
 194.30    29.30
 210.14    37.20
 250.30     0.00
 252.35    31.90
Name: trip_distance, Length: 916, dtype: float64

# What aggregation methods do we have?

- `min`
- `mean`
- `std`
- `median`
- `max`
- `count` -- how many non-`NaN` values?
- `sum`
- `nunique` -- how many distinct values were there

# Exercise: Olympic grouping

1. Load the Olympic data.
2. For each country in the G7 (US, Great Britain, Canada, France, Germany, Italy, Japan), what was the mean athelete height? Which 5 teams were tallest, on average?
3. For each team in the G7, what was the number of medals they accumulated?

https://practice.lernerpython.com/classroom/ce06963a8d/ex-63

In [14]:
!ls

__pycache__			BDTMSD-Python-2026-09-29.ipynb
airlines.dat			BDTMSD-Python-2026-10-02.ipynb
airports			burrito_current.csv
BDTMSD-Python-2026-07-21.ipynb	celebrity_deaths_2016.csv
BDTMSD-Python-2026-07-24.ipynb	greet.py
BDTMSD-Python-2026-07-28.ipynb	languages.csv
BDTMSD-Python-2026-07-31.ipynb	linux-etc-passwd.txt
BDTMSD-Python-2026-08-04.ipynb	macos-passwd.txt
BDTMSD-Python-2026-08-07.ipynb	menu.py
BDTMSD-Python-2026-08-11.ipynb	mini-access-log.txt
BDTMSD-Python-2026-08-14.ipynb	myconfig.txt
BDTMSD-Python-2026-08-18.ipynb	myfile.txt
BDTMSD-Python-2026-08-21.ipynb	mymod.py
BDTMSD-Python-2026-08-25.ipynb	nums.txt
BDTMSD-Python-2026-08-28.ipynb	passwd.txt
BDTMSD-Python-2026-09-01.ipynb	pyproject.toml
BDTMSD-Python-2026-09-04.ipynb	README.md
BDTMSD-Python-2026-09-08.ipynb	shoe-data.txt
BDTMSD-Python-2026-09-11.ipynb	taxi.csv
BDTMSD-Python-2026-09-15.ipynb	titanic3.csv
BDTMSD-Python-2026-09-18.ipynb	uv.lock
BDTMSD-Python-2026-09-25.ipynb	wcfile.txt

In [15]:
filename = '/Users/reuven/Data/olympic_athlete_events.zip'

df = pd.read_csv(filename)
df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [20]:
# 1. For each country in the G7 (US, Great Britain, Canada, France, Germany, Italy, Japan), what was the mean athelete height? Which 5 teams were tallest, on average?

(
    df
    .loc[ pd.col('Team').isin(['United States', 'Great Britain', 'Canada', 'France',
                                'Germany', 'Italy', 'Japan']) ,   # row selector
          'Height' ]
    .mean()
)

np.float64(174.9865015376943)

In [21]:

(
    df
    .loc[ pd.col('Team').isin(['United States', 'Great Britain', 'Canada', 'France',
                                'Germany', 'Italy', 'Japan'])]
    .groupby('Team')['Height'].mean()   # for each team, get the mean height
)

Team
Canada           174.931885
France           175.216527
Germany          177.213198
Great Britain    175.638320
Italy            175.220278
Japan            168.173326
United States    176.835467
Name: Height, dtype: float64

In [22]:
# get the 5 teams that are tallest

(
    df
    .loc[ pd.col('Team').isin(['United States', 'Great Britain', 'Canada', 'France',
                                'Germany', 'Italy', 'Japan'])]
    .groupby('Team')['Height'].mean()   # for each team, get the mean height
    .nlargest(5)
)

Team
Germany          177.213198
United States    176.835467
Great Britain    175.638320
Italy            175.220278
France           175.216527
Name: Height, dtype: float64

In [27]:
# how can I get the 5 largest mean heights from the entire data set?

(
    df
    .groupby('Team')['Height'].mean() 
    .nlargest(5)
)

Team
Puerto Rico-1           196.000000
England-1               193.000000
France/Great Britain    191.000000
Nadine                  190.000000
Ireland-1               189.666667
Name: Height, dtype: float64

In [30]:
# 2. For each team in the G7, what was the number of medals they accumulated?

(
    df
    .loc[ pd.col('Team').isin(['United States', 'Great Britain', 'Canada', 'France',
                                'Germany', 'Italy', 'Japan'])]
    .groupby('Team')['Medal'].count()
    
)

Team
Canada           1243
France           1550
Germany          1984
Great Britain    1673
Italy            1527
Japan             911
United States    5219
Name: Medal, dtype: int64

# What about more than one of each?

The rule of thumb in Pandas is that wherever you can use a single column (i.e., a name/string), you can pass a list of columns (i.e., a list of strings).

In [31]:
df = pd.read_csv('taxi.csv')

In [33]:
# maybe I want the mean for not just trip_distance, but also total_amount, for each passenger_count.

# outer [] are part of the syntax for groupby
# inner [] are to show that we have a list of columns we want to analyze

(
    df
    .groupby('passenger_count')[['trip_distance', 'total_amount']].mean() 
)

                 trip_distance  total_amount
passenger_count
0                     4.600000     25.570000
1                     3.092338     17.368569
2                     3.384387     18.406306
3                     3.342389     17.994704
4                     3.628901     18.881648
5                     3.182712     17.211269
6                     3.170976     17.401355

In [36]:
# maybe I want not just to group on passenger_count, but also on VendorID, the manufacturer.


results = (
    df
    .groupby(['passenger_count', 'VendorID'])['trip_distance'].mean() 
)

# this returns a series with a MULTI-index!

results

passenger_count  VendorID
0                1           4.600000
1                1           2.956456
                 2           3.262967
2                1           3.452027
                 2           3.328849
3                1           3.588535
                 2           3.187189
4                1           3.952239
                 2           3.440522
5                1           4.933333
                 2           3.172553
6                2           3.170976
Name: trip_distance, dtype: float64

In [37]:
results.loc[1]  # this returns the subset of rows where passenger_count is 1

VendorID
1    2.956456
2    3.262967
Name: trip_distance, dtype: float64

# more than one aggregation method

In [43]:
# if we want to invoke more than one aggregation method, we use the "agg" method and pass (as individual parameters)
# The aggregation methods, we want to run.

results = (
    df
    .groupby('passenger_count')['trip_distance'].agg(['mean', 'std'])
)

results

                     mean       std
passenger_count
0                4.600000  4.666905
1                3.092338  4.020187
2                3.384387  4.242826
3                3.342389  3.822041
4                3.628901  4.351369
5                3.182712  3.969468
6                3.170976  3.759807

# Any (or all!) of the three inputs to `groupby` can support multiples

# Exercise: Fancier grouping

1. Find the mean and standard deviation, in the Olympic data, for each team's height. If you also check median, what does that tell you about the data?
2. Find the mean for both height and weight
3. Find, for Season + Year, the mean height and weight.

https://practice.lernerpython.com/classroom/ce06963a8d/ex-67

In [44]:
df = pd.read_csv('/Users/reuven/Data/olympic_athlete_events.csv')

df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [46]:
# Find the mean and standard deviation, in the Olympic data, for each team's height. If you also check median, what does that tell you about the data?

(
    df
    .groupby('Team')['Height'].agg(['mean', 'std', 'median'])
)

                             mean        std  median
Team
30. Februar            171.500000   6.363961   171.5
A North American Team         NaN        NaN     NaN
Acipactli              174.666667   4.725816   173.0
Acturus                       NaN        NaN     NaN
Afghanistan            170.592593   7.778826   170.0
...                           ...        ...     ...
Zambia                 172.828125   8.260626   175.0
Zefyros                180.000000   2.828427   180.0
Zimbabwe               173.325175  10.400870   175.0
Zut                           NaN        NaN     NaN
rn-2                   176.000000        NaN   176.0

[1184 rows x 3 columns]

In [50]:
# Find the mean for both height and weight

    
(
    df
    .loc[ pd.col('Team').isin(['United States', 'Great Britain', 'Canada', 'France',
                                'Germany', 'Italy', 'Japan'])]
    .groupby('Team')[['Height', 'Weight']].mean()
)

                   Height     Weight
Team
Canada         174.931885  70.257556
France         175.216527  69.484337
Germany        177.213198  71.983220
Great Britain  175.638320  70.444283
Italy          175.220278  70.656526
Japan          168.173326  63.215977
United States  176.835467  72.407174

In [53]:
# Find, for Season + Year, the mean height and weight.

(
    df
             #year+season are category
                                    # height and weight in []
                                        # mean of both height and weight
    .groupby(['Year', 'Season'])[['Height', 'Weight']].mean()
)

                 Height     Weight
Year Season
1896 Summer  172.739130  71.387755
1900 Summer  176.637931  74.556962
1904 Summer  175.788732  72.197279
1906 Summer  178.206226  75.917073
1908 Summer  177.543158  75.386128
1912 Summer  177.447989  73.117450
1920 Summer  175.752282  73.106157
1924 Summer  175.239548  71.812018
     Winter  172.213483  69.560976
1928 Summer  175.331770  70.941791
     Winter  173.975410  71.625000
1932 Summer  174.371681  70.897980
     Winter  173.433673  67.363636
1936 Summer  176.112689  71.630363
     Winter  172.705882  70.051282
1948 Summer  176.600190  71.942308
     Winter  172.293103  68.540541
1952 Summer  174.183023  70.096173
     Winter  173.540000  69.191275
1956 Summer  174.116567  70.364200
     Winter  172.433140  70.554094
1960 Summer  173.310287  69.393811
     Winter  170.701493  68.136719
1964 Summer  173.690848  69.686692
     Winter  172.133674  69.840134
1968 Summer  174.087484  69.454786
     Winter  173.289689  70.261145
1972 Summer  174.745758  70.086422
     Winter  173.463415  69.495128
1976 Summer  175.053724  70.066143
     Winter  174.099032  70.531490
1980 Summer  175.634392  70.668078
     Winter  174.991354  70.968705
1984 Summer  175.573516  70.058133
     Winter  175.390194  71.099028
1988 Summer  175.683249  70.224268
     Winter  176.104249  72.002725
1992 Summer  176.382283  71.143607
     Winter  175.395332  71.116780
1994 Winter  175.169862  71.062100
1996 Summer  175.895121  70.903281
1998 Winter  174.581369  70.943734
2000 Summer  176.089721  71.119046
2002 Winter  174.702451  71.197070
2004 Summer  175.972850  71.280695
2006 Winter  174.623172  70.519354
2008 Summer  176.211062  71.397679
2010 Winter  174.918182  70.740863
2012 Summer  176.262469  71.319586
2014 Winter  174.816670  70.760111
2016 Summer  176.034266  70.988637

In [54]:
# don't want Pandas to reorder the values by the index when grouping? pass sort=False


(
    df
             #year+season are category
                                    # height and weight in []
                                        # mean of both height and weight
    .groupby(['Year', 'Season'], sort=False)[['Height', 'Weight']].mean()
)

                 Height     Weight
Year Season
1992 Summer  176.382283  71.143607
2012 Summer  176.262469  71.319586
1920 Summer  175.752282  73.106157
1900 Summer  176.637931  74.556962
1988 Winter  176.104249  72.002725
1992 Winter  175.395332  71.116780
1994 Winter  175.169862  71.062100
1932 Summer  174.371681  70.897980
2002 Winter  174.702451  71.197070
1952 Summer  174.183023  70.096173
1980 Winter  174.991354  70.968705
2000 Summer  176.089721  71.119046
1996 Summer  175.895121  70.903281
1912 Summer  177.447989  73.117450
1924 Summer  175.239548  71.812018
2014 Winter  174.816670  70.760111
1948 Summer  176.600190  71.942308
1998 Winter  174.581369  70.943734
2006 Winter  174.623172  70.519354
2008 Summer  176.211062  71.397679
2016 Summer  176.034266  70.988637
2004 Summer  175.972850  71.280695
1960 Winter  170.701493  68.136719
1964 Winter  172.133674  69.840134
1984 Winter  175.390194  71.099028
     Summer  175.573516  70.058133
1968 Summer  174.087484  69.454786
1972 Summer  174.745758  70.086422
1988 Summer  175.683249  70.224268
1936 Summer  176.112689  71.630363
1952 Winter  173.540000  69.191275
1956 Winter  172.433140  70.554094
     Summer  174.116567  70.364200
1960 Summer  173.310287  69.393811
1928 Summer  175.331770  70.941791
1976 Summer  175.053724  70.066143
1980 Summer  175.634392  70.668078
1964 Summer  173.690848  69.686692
2010 Winter  174.918182  70.740863
1968 Winter  173.289689  70.261145
1906 Summer  178.206226  75.917073
1972 Winter  173.463415  69.495128
1976 Winter  174.099032  70.531490
1924 Winter  172.213483  69.560976
1904 Summer  175.788732  72.197279
1928 Winter  173.975410  71.625000
1908 Summer  177.543158  75.386128
1948 Winter  172.293103  68.540541
1932 Winter  173.433673  67.363636
1936 Winter  172.705882  70.051282
1896 Summer  172.739130  71.387755

In [55]:
help(df.groupby)

Help on method groupby in module pandas.core.frame:

groupby(
    by=None,
    level: IndexLabel | None = None,
    *,
    as_index: bool = True,
    sort: bool = True,
    group_keys: bool = True,
    observed: bool = True,
    dropna: bool = True
) -> DataFrameGroupBy method of pandas.DataFrame instance
    Group DataFrame using a mapper or by a Series of columns.

    A groupby operation involves some combination of splitting the
    object, applying a function, and combining the results. This can be
    used to group large amounts of data and compute operations on these
    groups.

    Parameters
    ----------
    by : mapping, function, label, pd.Grouper or list of such
        Used to determine the groups for the groupby.
        If ``by`` is a function, it's called on each value of the object's
        index. If a dict or Series is passed, the Series or dict VALUES
        will be used to determine the groups (the Series' values are first
        aligned; see ``.align()`` method). If a list or ndarray of length
        equal to the number of rows is passed (see the `groupby user guide
        <https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#splitting-an-object-into-groups>`_),
        the values are used as-is to determine the groups. A label or list
        of labels may be passed to group by the columns in ``self``.
        Notice that a tuple is interpreted as a (single) key.
    level : int, level name, or sequence of such, default None
        If the axis is a MultiIndex (hierarchical), group by a particular
        level or levels. Do not specify both ``by`` and ``level``.
    as_index : bool, default True
        Return object with group labels as the
        index. Only relevant for DataFrame input. as_index=False is
        effectively "SQL-style" grouped output. This argument has no effect
        on filtrations (see the `filtrations in the user guide
        <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#filtration>`_),
        such as ``head()``, ``tail()``, ``nth()`` and in transformations
        (see the `transformations in the user guide
        <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#transformation>`_).
    sort : bool, default True
        Sort group keys. Get better performance by turning this off.
        Note this does not influence the order of observations within each
        group. Groupby preserves the order of rows within each group. If False,
        the groups will appear in the same order as they did in the original
        DataFrame.
        This argument has no effect on filtrations (see the `filtrations
        in the user guide
        <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#filtration>`_),
        such as ``head()``, ``tail()``, ``nth()`` and in transformations
        (see the `transformations in the user guide
        <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#transformation>`_).

        .. versionchanged:: 2.0.0

            Specifying ``sort=False`` with an ordered categorical grouper will no
            longer sort the values.

    group_keys : bool, default True
        When calling apply and the ``by`` argument produces a like-indexed
        (i.e. :ref:`a transform <groupby.transform>`) result, add group keys to
        index to identify pieces. By default group keys are not included
        when the result's index (and column) labels match the inputs, and
        are included otherwise.

        .. versionchanged:: 2.0.0

           ``group_keys`` now defaults to ``True``.

    observed : bool, default True
        This only applies if any of the groupers are Categoricals.
        If True: only show observed values for categorical groupers.
        If False: show all values for categorical groupers.

        .. versionchanged:: 3.0.0

            The default value is now ``True``.

    dropna : bool, default True
        If True, and if group keys contain NA values, NA values together
        with row/column will be dropped.
        If False, NA values will also be treated as the key in groups.

    Returns
    -------
    pandas.api.typing.DataFrameGroupBy
        Returns a groupby object that contains information about the groups.

    See Also
    --------
    resample : Convenience method for frequency conversion and resampling
        of time series.

    Notes
    -----
    See the `user guide
    <https://pandas.pydata.org/pandas-docs/stable/groupby.html>`__ for more
    detailed usage and examples, including splitting an object into groups,
    iterating through groups, selecting a group, aggregation, and more.

    The implementation of groupby is hash-based, meaning in particular that
    objects that compare as equal will be considered to be in the same group.
    An exception to this is that pandas has special handling of NA values:
    any NA values will be collapsed to a single group, regardless of how
    they compare. See the user guide linked above for more details.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     {
    ...         "Animal": ["Falcon", "Falcon", "Parrot", "Parrot"],
    ...         "Max Speed": [380.0, 370.0, 24.0, 26.0],
    ...     }
    ... )
    >>> df
       Animal  Max Speed
    0  Falcon      380.0
    1  Falcon      370.0
    2  Parrot       24.0
    3  Parrot       26.0
    >>> df.groupby(["Animal"]).mean()
            Max Speed
    Animal
    Falcon      375.0
    Parrot       25.0

    **Hierarchical Indexes**

    We can groupby different levels of a hierarchical index
    using the `level` parameter:

    >>> arrays = [
    ...     ["Falcon", "Falcon", "Parrot", "Parrot"],
    ...     ["Captive", "Wild", "Captive", "Wild"],
    ... ]
    >>> index = pd.MultiIndex.from_arrays(arrays, names=("Animal", "Type"))
    >>> df = pd.DataFrame({"Max Speed": [390.0, 350.0, 30.0, 20.0]}, index=index)
    >>> df
                    Max Speed
    Animal Type
    Falcon Captive      390.0
           Wild         350.0
    Parrot Captive       30.0
           Wild          20.0
    >>> df.groupby(level=0).mean()
            Max Speed
    Animal
    Falcon      370.0
    Parrot       25.0
    >>> df.groupby(level="Type").mean()
             Max Speed
    Type
    Captive      210.0
    Wild         185.0

    We can also choose to include NA in group keys or not by setting
    `dropna` parameter, the default setting is `True`.

    >>> arr = [[1, 2, 3], [1, None, 4], [2, 1, 3], [1, 2, 2]]
    >>> df = pd.DataFrame(arr, columns=["a", "b", "c"])

    >>> df.groupby(by=["b"]).sum()
        a   c
    b
    1.0 2   3
    2.0 2   5

    >>> df.groupby(by=["b"], dropna=False).sum()
        a   c
    b
    1.0 2   3
    2.0 2   5
    NaN 1   4

    >>> arr = [["a", 12, 12], [None, 12.3, 33.0], ["b", 12.3, 123], ["a", 1, 1]]
    >>> df = pd.DataFrame(arr, columns=["a", "b", "c"])

    >>> df.groupby(by="a").sum()
        b     c
    a
    a   13.0   13.0
    b   12.3  123.0

    >>> df.groupby(by="a", dropna=False).sum()
        b     c
    a
    a   13.0   13.0
    b   12.3  123.0
    NaN 12.3   33.0

    When using ``.apply()``, use ``group_keys`` to include or exclude the
    group keys. The ``group_keys`` argument defaults to ``True`` (include).

    >>> df = pd.DataFrame(
    ...     {
    ...         "Animal": ["Falcon", "Falcon", "Parrot", "Parrot"],
    ...         "Max Speed": [380.0, 370.0, 24.0, 26.0],
    ...     }
    ... )
    >>> df.groupby("Animal", group_keys=True)[["Max Speed"]].apply(lambda x: x)
              Max Speed
    Animal
    Falcon 0      380.0
           1      370.0
    Parrot 2       24.0
           3       26.0

    >>> df.groupby("Animal", group_keys=False)[["Max Speed"]].apply(lambda x: x)
       Max Speed
    0      380.0
    1      370.0
    2       24.0
    3       26.0

In [57]:
(
    df
    .groupby(['Year', 'Season'])['Height'].mean()
)

Year  Season
1896  Summer    172.739130
1900  Summer    176.637931
1904  Summer    175.788732
1906  Summer    178.206226
1908  Summer    177.543158
1912  Summer    177.447989
1920  Summer    175.752282
1924  Summer    175.239548
      Winter    172.213483
1928  Summer    175.331770
      Winter    173.975410
1932  Summer    174.371681
      Winter    173.433673
1936  Summer    176.112689
      Winter    172.705882
1948  Summer    176.600190
      Winter    172.293103
1952  Summer    174.183023
      Winter    173.540000
1956  Summer    174.116567
      Winter    172.433140
1960  Summer    173.310287
      Winter    170.701493
1964  Summer    173.690848
      Winter    172.133674
1968  Summer    174.087484
      Winter    173.289689
1972  Summer    174.745758
      Winter    173.463415
1976  Summer    175.053724
      Winter    174.099032
1980  Summer    175.634392
      Winter    174.991354
1984  Summer    175.573516
      Winter    175.390194
1988  Summer    175.683249
      Winter    176.104249
1992  Summer    176.382283
      Winter    175.395332
1994  Winter    175.169862
1996  Summer    175.895121
1998  Winter    174.581369
2000  Summer    176.089721
2002  Winter    174.702451
2004  Summer    175.972850
2006  Winter    174.623172
2008  Summer    176.211062
2010  Winter    174.918182
2012  Summer    176.262469
2014  Winter    174.816670
2016  Summer    176.034266
Name: Height, dtype: float64

This works, and it has the right calculations. But it's very long. Many people prefer to have it in a more rectangular shape.

What does that mean?

Because the index is a *multi-index*, with more than one level, I can send one particular level to be back as a regular column. Or I can send one particular level to be the column names.

In [58]:
(
    df
    .groupby(['Year', 'Season'])['Height'].mean()
    .unstack('Season')  # unstack means: move it from being part of the index to being part of the column
)

Season      Summer      Winter
Year
1896    172.739130         NaN
1900    176.637931         NaN
1904    175.788732         NaN
1906    178.206226         NaN
1908    177.543158         NaN
1912    177.447989         NaN
1920    175.752282         NaN
1924    175.239548  172.213483
1928    175.331770  173.975410
1932    174.371681  173.433673
1936    176.112689  172.705882
1948    176.600190  172.293103
1952    174.183023  173.540000
1956    174.116567  172.433140
1960    173.310287  170.701493
1964    173.690848  172.133674
1968    174.087484  173.289689
1972    174.745758  173.463415
1976    175.053724  174.099032
1980    175.634392  174.991354
1984    175.573516  175.390194
1988    175.683249  176.104249
1992    176.382283  175.395332
1994           NaN  175.169862
1996    175.895121         NaN
1998           NaN  174.581369
2000    176.089721         NaN
2002           NaN  174.702451
2004    175.972850         NaN
2006           NaN  174.623172
2008    176.211062         NaN
2010           NaN  174.918182
2012    176.262469         NaN
2014           NaN  174.816670
2016    176.034266         NaN

# Pivot table

A pivot table (in Pandas) is a data frame that you created with the `pivot_table` method. It's basically a 2D groupby:

- One categorical's unique values are used for the index (rows)
- Another categorical's unique values are used for the column names.
- We need a data column
- We need an aggregation method

In [60]:
(
    df
    .pivot_table(index='Year',
                 columns='Season',
                 values='Height',
                 aggfunc='mean')
)

Season      Summer      Winter
Year
1896    172.739130         NaN
1900    176.637931         NaN
1904    175.788732         NaN
1906    178.206226         NaN
1908    177.543158         NaN
1912    177.447989         NaN
1920    175.752282         NaN
1924    175.239548  172.213483
1928    175.331770  173.975410
1932    174.371681  173.433673
1936    176.112689  172.705882
1948    176.600190  172.293103
1952    174.183023  173.540000
1956    174.116567  172.433140
1960    173.310287  170.701493
1964    173.690848  172.133674
1968    174.087484  173.289689
1972    174.745758  173.463415
1976    175.053724  174.099032
1980    175.634392  174.991354
1984    175.573516  175.390194
1988    175.683249  176.104249
1992    176.382283  175.395332
1994           NaN  175.169862
1996    175.895121         NaN
1998           NaN  174.581369
2000    176.089721         NaN
2002           NaN  174.702451
2004    175.972850         NaN
2006           NaN  174.623172
2008    176.211062         NaN
2010           NaN  174.918182
2012    176.262469         NaN
2014           NaN  174.816670
2016    176.034266         NaN

In [61]:
(
    df
    .pivot_table(index='Year',
                 columns='Season',
                 values='Height',
                 aggfunc='mean')
    .stack()
)

Year  Season
1896  Summer    172.739130
      Winter           NaN
1900  Summer    176.637931
      Winter           NaN
1904  Summer    175.788732
                   ...
2012  Winter           NaN
2014  Summer           NaN
      Winter    174.816670
2016  Summer    176.034266
      Winter           NaN
Length: 70, dtype: float64

# Where would I use a pivot table?

Anywhere that you have two categorical columns in a data frame.

- Department vs. geography
- Product vs. sales

# Pandas offers

- `pivot_table`
- `pivot` -- this is basically just a reshaping of data, rather than actual calculations

# Exercise: Olympic pivots

1. Load up the Olympic data
2. Create a data frame in whihc the rows are labeled `Sport` and the columns are `Sex`. Show the mean height for each intersection.
3. Do the same thing for `Height` and `Weight`. What happens if you pass a list of columns, rather than just one, to `pivot_table`

https://practice.lernerpython.com/classroom/ce06963a8d/ex-64

In [62]:
df = pd.read_csv('/Users/reuven/data/olympic_athlete_events.csv')

df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [63]:
# Create a data frame in which the rows are labeled Sport and the columns are Sex. Show the mean height for each intersection.

(
    df
    .groupby(['Sport', 'Sex'])['Height'].mean()
)

Sport          Sex
Aeronautics    M             NaN
Alpine Skiing  F      167.221001
               M      177.891374
Alpinism       F             NaN
               M             NaN
                         ...
Water Polo     M      186.801739
Weightlifting  F      160.467391
               M      169.153061
Wrestling      F      163.865132
               M      172.870686
Name: Height, Length: 116, dtype: float64

In [64]:
# index (rows) - Sport
# columns - Sex
# values - Height
# aggfunc - mean

(
    df
    .pivot_table(index='Sport',
                 columns='Sex',
                 values='Height',
                 aggfunc='mean')
)

Sex                                 F           M
Sport
Alpine Skiing              167.221001  177.891374
Archery                    167.166483  178.477842
Art Competitions           160.000000  174.896552
Athletics                  169.285714  179.768303
Badminton                  168.438519  179.620787
Baseball                          NaN  182.599291
Basketball                 182.454836  194.872624
Beach Volleyball           178.866667  193.290909
Biathlon                   166.540541  178.856281
Bobsleigh                  173.181818  181.992015
Boxing                     168.800000  172.888199
Canoeing                   169.628995  181.212532
Cross Country Skiing       166.650819  177.757682
Curling                    167.520362  180.709251
Cycling                    168.018629  177.745402
Diving                     161.173604  171.555352
Equestrianism              167.875755  176.563172
Fencing                    168.954292  180.014125
Figure Skating             160.610849  176.062271
Football                   167.676142  177.480339
Freestyle Skiing           164.777262  176.442424
Golf                       168.733333  178.985915
Gymnastics                 156.143325  167.644438
Handball                   174.840278  188.778373
Hockey                     166.125267  176.852577
Ice Hockey                 168.209549  180.991444
Jeu De Paume                      NaN  178.500000
Judo                       166.267000  177.487500
Lacrosse                          NaN  174.000000
Luge                       169.065527  179.242483
Modern Pentathlon          170.073171  179.087688
Motorboating                      NaN  181.000000
Nordic Combined                   NaN  176.504464
Polo                              NaN  175.500000
Racquets                          NaN  176.000000
Rhythmic Gymnastics        167.870253         NaN
Rowing                     176.771079  186.882698
Rugby                             NaN  176.096774
Rugby Sevens               167.636986  182.834437
Sailing                    169.510808  180.156897
Shooting                   164.932934  175.977163
Short Track Speed Skating  164.530447  175.611482
Skeleton                   167.923077  181.072727
Ski Jumping                164.600000  176.579710
Snowboarding               166.298077  178.526012
Softball                   169.395089         NaN
Speed Skating              167.420704  179.183060
Swimming                   171.468735  184.310928
Synchronized Swimming      168.481481         NaN
Table Tennis               165.064965  177.008630
Taekwondo                  170.811644  182.418301
Tennis                     172.335736  184.847806
Trampolining               161.733333  171.368421
Triathlon                  166.996183  180.195489
Tug-Of-War                        NaN  182.480000
Volleyball                 179.494983  193.265660
Water Polo                 175.563525  186.801739
Weightlifting              160.467391  169.153061
Wrestling                  163.865132  172.870686

In [65]:
# Do the same thing for Height and Weight. What happens if you pass a list of columns, rather than just one, to pivot_table?


(
    df
    .pivot_table(index='Sport',
                 columns='Sex',
                 values=['Height', 'Weight'],
                 aggfunc='mean')
)

                               Height                 Weight
Sex                                 F           M          F          M
Sport
Alpine Skiing              167.221001  177.891374  62.640307  78.626035
Archery                    167.166483  178.477842  62.013575  77.066866
Art Competitions           160.000000  174.896552        NaN  75.290909
Athletics                  169.285714  179.768303  60.239798  73.839129
Badminton                  168.438519  179.620787  61.586364  74.362536
Baseball                          NaN  182.599291        NaN  85.707792
Basketball                 182.454836  194.872624  73.685170  91.683529
Beach Volleyball           178.866667  193.290909  68.350943  89.512821
Biathlon                   166.540541  178.856281  57.306586  72.632123
Bobsleigh                  173.181818  181.992015  72.804196  90.387385
Boxing                     168.800000  172.888199  61.836066  65.296280
Canoeing                   169.628995  181.212532  64.878906  79.972378
Cross Country Skiing       166.650819  177.757682  57.488018  71.700832
Curling                    167.520362  180.709251  62.888350  81.465686
Cycling                    168.018629  177.745402  59.770553  72.190234
Diving                     161.173604  171.555352  53.566563  67.069378
Equestrianism              167.875755  176.563172  58.601908  70.924559
Fencing                    168.954292  180.014125  60.656144  75.381977
Figure Skating             160.610849  176.062271  49.861039  69.591644
Football                   167.676142  177.480339  60.925813  73.086644
Freestyle Skiing           164.777262  176.442424  58.352459  74.648148
Golf                       168.733333  178.985915  63.436364  79.245283
Gymnastics                 156.143325  167.644438  47.791276  63.343605
Handball                   174.840278  188.778373  68.876851  89.387914
Hockey                     166.125267  176.852577  60.530935  73.343761
Ice Hockey                 168.209549  180.991444  65.712865  83.775593
Jeu De Paume                      NaN  178.500000        NaN        NaN
Judo                       166.267000  177.487500  67.067164  83.573945
Lacrosse                          NaN  174.000000        NaN  76.714286
Luge                       169.065527  179.242483  66.908832  80.803311
Modern Pentathlon          170.073171  179.087688  58.310976  72.068824
Motorboating                      NaN  181.000000        NaN  77.000000
Nordic Combined                   NaN  176.504464        NaN  66.909560
Polo                              NaN  175.500000        NaN        NaN
Racquets                          NaN  176.000000        NaN        NaN
Rhythmic Gymnastics        167.870253         NaN  48.760976        NaN
Rowing                     176.771079  186.882698  70.102214  83.665663
Rugby                             NaN  176.096774        NaN  77.533333
Rugby Sevens               167.636986  182.834437  66.628378  91.006623
Sailing                    169.510808  180.156897  62.777268  78.849712
Shooting                   164.932934  175.977163  61.143243  77.834960
Short Track Speed Skating  164.530447  175.611482  57.123139  71.401869
Skeleton                   167.923077  181.072727  61.000000  82.018349
Ski Jumping                164.600000  176.579710  52.615385  65.245881
Snowboarding               166.298077  178.526012  60.444175  76.861598
Softball                   169.395089         NaN  67.471655        NaN
Speed Skating              167.420704  179.183060  62.010046  76.300403
Swimming                   171.468735  184.310928  61.482748  78.040567
Synchronized Swimming      168.481481         NaN  55.863529        NaN
Table Tennis               165.064965  177.008630  58.027778  71.414239
Taekwondo                  170.811644  182.418301  61.136824  74.653595
Tennis                     172.335736  184.847806  62.094398  78.842912
Trampolining               161.733333  171.368421  52.893333  65.837838
Triathlon                  166.996183  180.195489  54.724138  68.803774
Tug-Of-War                        NaN  182.480000        NaN  95.615385
Volleyball                 179.494983  193.265660  69.333779  86.925926
Water Polo                 175.563525  186.801739  70.180328  87.706172
Weightlifting              160.467391  169.153061  67.724622  80.251796
Wrestling                  163.865132  172.870686  60.554455  76.400640

In [ ]:

(
    df
    .pivot_table(index='Sport',
                 columns='Sex',
                 values=['Height', 'Weight'],
                 aggfunc='mean',
                ma)
)