# Agenda

- File-loading options (for CSV)
- Excel files
- (other formats as well, and retrieving from the Internet)
- Sorting
- Grouping

In [1]:
import pandas as pd
from pandas import Series, DataFrame

# `read_csv` options

If you're going to read a CSV file into Pandas, you can give it many different hints as to how to read the data, and what to do with it. 

Here are a few common options that you might want to use:

- `sep` -- what is the separator between fields? Normally, by default, it's a comma (`','`). It's pretty common for it to also be a tab character, which we write as `'\t'`. It can also be other things, e.g., `'::'`. If you don't get the separator right, you'll almost certainly get a one-column data frame back from `read_csv`, and then it becomes super obvious.
- `usecols` -- a list of columns you want to include from the file. You can either name the columns using the names on the first line (assuming that they are column names), or you can number them, starting at 0, from the first one.
- `header` -- on what line of the file do we get the names of the columns? By default, this is assumed to be 0 (i.e., the first line). But if it's on line 10, then you'll say that, and lines 0-9 will be ignored by `read_csv`. If there is no header in the CSV, you can say `header=None`, and then the columns will only be numbered.
- `index_col` -- what column should be used as the data frame's index? This is basically the same as invoking `set_index` on a particular column after you have created the data frame.
- `names` -- you can pass a list of names, the same length as the number of columns, and these will be used instead of numbers or whatever names were passed. If you use the `names` keyword argument, then `usecols` cannot use names; you need to use numbers.

These are options for `read_csv`, but there are methods to read from a very large number of file formats, and many of them support (some of these) options, as well.

In [3]:
filename = 'taxi.csv'

df = pd.read_csv(filename)
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,2,2015-06-02 11:19:29,2015-06-02 11:47:52,1,1.63,-73.954430,40.764141,1,N,-73.974754,40.754093,2,17.0,0.0,0.5,0.00,0.0,0.3,17.80
1,2,2015-06-02 11:19:30,2015-06-02 11:27:56,1,0.46,-73.971443,40.758942,1,N,-73.978539,40.761909,1,6.5,0.0,0.5,1.00,0.0,0.3,8.30
2,2,2015-06-02 11:19:31,2015-06-02 11:30:30,1,0.87,-73.978111,40.738434,1,N,-73.990273,40.745438,1,8.0,0.0,0.5,2.20,0.0,0.3,11.00
3,2,2015-06-02 11:19:31,2015-06-02 11:39:02,1,2.13,-73.945892,40.773529,1,N,-73.971527,40.760330,1,13.5,0.0,0.5,2.86,0.0,0.3,17.16
4,1,2015-06-02 11:19:32,2015-06-02 11:32:49,1,1.40,-73.979088,40.776772,1,N,-73.982162,40.758999,2,9.5,0.0,0.5,0.00,0.0,0.3,10.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,1,2015-06-01 00:12:59,2015-06-01 00:24:18,1,2.70,-73.947792,40.814972,1,N,-73.973358,40.783638,2,11.0,0.5,0.5,0.00,0.0,0.3,12.30
9995,1,2015-06-01 00:12:59,2015-06-01 00:28:16,1,4.50,-74.004066,40.747818,1,N,-73.953758,40.779285,1,16.0,0.5,0.5,3.00,0.0,0.3,20.30
9996,2,2015-06-01 00:13:00,2015-06-01 00:37:25,1,5.59,-73.994377,40.766102,1,N,-73.903206,40.750546,2,21.0,0.5,0.5,0.00,0.0,0.3,22.30
9997,2,2015-06-01 00:13:02,2015-06-01 00:19:10,6,1.54,-73.978302,40.748531,1,N,-73.989166,40.762852,2,6.5,0.5,0.5,0.00,0.0,0.3,7.80
9998,1,2015-06-01 00:13:04,2015-06-01 00:36:33,1,5.80,-73.983215,40.726414,1,N,-73.924133,40.701645,1,21.0,0.5,0.5,4.45,0.0,0.3,26.75

In [4]:
# usecols

filename = 'taxi.csv'

df = pd.read_csv(filename,
                usecols=['passenger_count', 'trip_distance', 'total_amount'])
df

      passenger_count  trip_distance  total_amount
0                   1           1.63         17.80
1                   1           0.46          8.30
2                   1           0.87         11.00
3                   1           2.13         17.16
4                   1           1.40         10.30
...               ...            ...           ...
9994                1           2.70         12.30
9995                1           4.50         20.30
9996                1           5.59         22.30
9997                6           1.54          7.80
9998                1           5.80         26.75

[9999 rows x 3 columns]

In [5]:
# usecols + index_col

filename = 'taxi.csv'

df = pd.read_csv(filename,
                usecols=['tpep_pickup_datetime', 'passenger_count', 'trip_distance', 'total_amount'],
                index_col='tpep_pickup_datetime')
df

                      passenger_count  trip_distance  total_amount
tpep_pickup_datetime
2015-06-02 11:19:29                 1           1.63         17.80
2015-06-02 11:19:30                 1           0.46          8.30
2015-06-02 11:19:31                 1           0.87         11.00
2015-06-02 11:19:31                 1           2.13         17.16
2015-06-02 11:19:32                 1           1.40         10.30
...                               ...            ...           ...
2015-06-01 00:12:59                 1           2.70         12.30
2015-06-01 00:12:59                 1           4.50         20.30
2015-06-01 00:13:00                 1           5.59         22.30
2015-06-01 00:13:02                 6           1.54          7.80
2015-06-01 00:13:04                 1           5.80         26.75

[9999 rows x 3 columns]

In [13]:
# rename the columns with "names"

filename = 'taxi.csv'

df = pd.read_csv(filename,
                usecols=[1, 3, 4, 18],   # grab columns by numeric index
                header=0,                # we have column names
                names=['pickup_at', 'num_passengers', 'distance', 'amount'],  # we ignore the column names
                index_col='pickup_at')
df

                     num_passengers  distance  amount
pickup_at
2015-06-02 11:19:29               1      1.63   17.80
2015-06-02 11:19:30               1      0.46    8.30
2015-06-02 11:19:31               1      0.87   11.00
2015-06-02 11:19:31               1      2.13   17.16
2015-06-02 11:19:32               1      1.40   10.30
...                             ...       ...     ...
2015-06-01 00:12:59               1      2.70   12.30
2015-06-01 00:12:59               1      4.50   20.30
2015-06-01 00:13:00               1      5.59   22.30
2015-06-01 00:13:02               6      1.54    7.80
2015-06-01 00:13:04               1      5.80   26.75

[9999 rows x 3 columns]

# Exercise: Titanic

1. Load `titanic.csv` into a data frame.
2. Find the mean age of people who survived.
3. Find the mean age of men who survived.
4. Find the mean age of women who survived, and got on board in Southampton ("S").

Load the minimum data you need to answer these questions.

https://practice.lernerpython.com/classroom/ce06963a8d/ex-60

In [20]:
filename = 'titanic3.csv'

df = (
    pd
    .read_csv(filename,
              usecols=['survived', 'age', 'sex', 'embarked'])
    .dropna()
)

df

      survived     sex      age embarked
0          1.0  female  29.0000        S
1          1.0    male   0.9167        S
2          0.0  female   2.0000        S
3          0.0    male  30.0000        S
4          0.0  female  25.0000        S
...        ...     ...      ...      ...
1301       0.0    male  45.5000        C
1304       0.0  female  14.5000        C
1306       0.0    male  26.5000        C
1307       0.0    male  27.0000        C
1308       0.0    male  29.0000        S

[1044 rows x 4 columns]

In [23]:
# Find the mean age of people who survived.

(
    df
    .loc[ 
        pd.col('survived') == 1   # row selector
        ,
        'age'                     # column selector
        ]
    .mean()
)

np.float64(28.81901976470588)

In [24]:
# mean age of non-survivors

(
    df
    .loc[ 
        pd.col('survived') == 0   # row selector
        ,
        'age'                     # column selector
        ]
    .mean()
)

np.float64(30.54536882067851)

In [26]:
# Find the mean age of men who survived.

(
    df
    .loc[ pd.col('survived') == 1 ]   # first .loc -- row selector for survived
    .loc[ 
        pd.col('sex') == 'male'   # second .loc -- row selector keeping males
        ,
        'age'                     # column selector -- keep the age column
        ]
    .mean()
)

np.float64(26.977777777777778)

In [27]:
# Find the mean age of women who survived, and got on board in Southampton ("S").


(
    df
    .loc[ pd.col('survived') == 1 ]   # first .loc -- row selector for survived
    .loc[ pd.col('embarked') == 'S' ] # second .loc -- only those got on in Southampton
    .loc[ 
        pd.col('sex') == 'female'   # second .loc -- row selector keeping females
        ,
        'age'                     # column selector -- keep the age column
        ]
    .mean()
)

np.float64(29.10416702127659)

# Excel files

Excel files are a bit better than CSV, in that they typically tag their data with appropriate data types, so Pandas doesn't have to work as hard. Also, it can have multiple sheets in a file -- so there will be times when you need to specify what sheet you want. You can use many of the same options as you did with `read_csv`, including -- `header`, `usecols`, and `index_col`. 

Pandas relies on other Python packages to read and load Excel files. If you don't have any installed, then invoking `read_excel` will give an error message, suggesting which package to install.

A big, important option is `sheet_name` -- if there is more than one sheet, then invoking `read_excel` returns the first one, which is often an explanatory sheet. You can name the sheet with a string (its name) or by passing an integer indicating which sheet you want. You can even ask for a list of indexes/names.

In [31]:
df = pd.read_excel('/Users/reuven/Downloads/DCOILWTICO.xlsx', sheet_name='Daily') 
df.head(10)

  observation_date  DCOILWTICO
0       1986-01-02       25.56
1       1986-01-03       26.00
2       1986-01-06       26.53
3       1986-01-07       25.85
4       1986-01-08       25.87
5       1986-01-09       26.03
6       1986-01-10       25.65
7       1986-01-13       25.08
8       1986-01-14       24.97
9       1986-01-15       25.18

# Exercise: Oil prices

1. Load the data into a Pandas data frame. Make the date column into the index. The other will contain the daily oil price.
2. On what day (in this data set) was the price the highest? What was that price?
3. On what day (in this data set) was the price the lowest? What was that price?
4. Is the most recent price above or below the mean + median in the data set?

https://practice.lernerpython.com/classroom/ce06963a8d/ex-61

In [32]:
df = pd.read_excel('/Users/reuven/Downloads/DCOILWTICO.xlsx', sheet_name='Daily')

In [33]:
df

      observation_date  DCOILWTICO
0           1986-01-02       25.56
1           1986-01-03       26.00
2           1986-01-06       26.53
3           1986-01-07       25.85
4           1986-01-08       25.87
...                ...         ...
10619       2026-09-16      103.62
10620       2026-09-17      103.21
10621       2026-09-18      101.44
10622       2026-09-21       96.97
10623       2026-09-22       96.41

[10624 rows x 2 columns]