# Agenda

1. Useful methods + attributes
2. `NaN` and data frames
3. Boolean indexes and data frames
4. Adding columns
5. (Finally!) Files

In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [2]:
df = DataFrame([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]],
               index=list('abcd'),
               columns=list('xyz'))
df

     x    y    z
a   10   20   30
b   40   50   60
c   70   80   90
d  100  110  120

In [3]:
# if I want the mean of a given column, I can grab that column and run mean

df['x'].mean()

np.float64(55.0)

In [4]:
# what happens if I invoke the mean method on the data frame, rather than one column?

df.mean()

x    55.0
y    65.0
z    75.0
dtype: float64

In [5]:
df['z'].max()

np.int64(120)

In [6]:
df.max()

x    100
y    110
z    120
dtype: int64

The general rule of thumb is that if you run a series method on a data frame, the method is run on each column, and you get a result for each column, labeled with the column's name.

However... if you want, you can often invoke the method passing the "axis" keyword argument. If you pass "axis='columns'", then it'll go the other way.

In [7]:
df

     x    y    z
a   10   20   30
b   40   50   60
c   70   80   90
d  100  110  120

In [8]:
df.max()

x    100
y    110
z    120
dtype: int64

In [10]:
df.max(axis='columns')

a     30
b     60
c     90
d    120
dtype: int64

In [11]:
df.max(axis=0)  # in NumPy, you have to say 0 or 1 for the axis, and 0 is the "default" axis

x    100
y    110
z    120
dtype: int64

In [12]:
df.max(axis=1)

a     30
b     60
c     90
d    120
dtype: int64

# More general series->data frame method rule of thumb:

- If the series method returns a single value, the data frame method will return a series
- If the series method returns a series, the data frame method will return a data frame

In [13]:
df['x'].describe()  # this returns a series, info about our column

count      4.000000
mean      55.000000
std       38.729833
min       10.000000
25%       32.500000
50%       55.000000
75%       77.500000
max      100.000000
Name: x, dtype: float64

In [14]:
df.describe()  # now I'll get a data frame back, with one column per column in df -- it'll only show numeric columns by default

                x           y           z
count    4.000000    4.000000    4.000000
mean    55.000000   65.000000   75.000000
std     38.729833   38.729833   38.729833
min     10.000000   20.000000   30.000000
25%     32.500000   42.500000   52.500000
50%     55.000000   65.000000   75.000000
75%     77.500000   87.500000   97.500000
max    100.000000  110.000000  120.000000

# NaN values 

In a series, we have three methods we can use:

- `dropna` -- returns only non-NaN values
- `fillna(n)` -- returns a new series in which NaN is replaced with n
- `interpolate` -- returns a series where `NaN` is replaced by the mean of its neighbors or (more generally) a linear function

In a data frame:

- `dropna` -- returns a data frame, where any ROW with `NaN` is removed
- `fillna` -- returns a data frame, where all `NaN` values are replaced ... or you can pass it a series, and fill a different value for each column
- `interpolate` -- doesn't really change, but works per column

In [15]:
df

     x    y    z
a   10   20   30
b   40   50   60
c   70   80   90
d  100  110  120

In [17]:
df.loc['b', 'y'] = float('nan')
df.loc['a', 'z'] = float('nan')
df.loc['a', 'x'] = float('nan')
df.loc['d', 'y'] = float('nan')

In [18]:
df

       x     y      z
a    NaN  20.0    NaN
b   40.0   NaN   60.0
c   70.0  80.0   90.0
d  100.0   NaN  120.0

In [19]:
df.dropna()

      x     y     z
c  70.0  80.0  90.0

In [20]:
# what if you want to keep some of the NaN values? Some columns are more important than others...

df.dropna(thresh=2)  # this means: If there are 2 good values, keep the column

       x     y      z
b   40.0   NaN   60.0
c   70.0  80.0   90.0
d  100.0   NaN  120.0

In [21]:
df.dropna(subset='x')  # only count 'x' when looking for NaN

       x     y      z
b   40.0   NaN   60.0
c   70.0  80.0   90.0
d  100.0   NaN  120.0

In [22]:
df

       x     y      z
a    NaN  20.0    NaN
b   40.0   NaN   60.0
c   70.0  80.0   90.0
d  100.0   NaN  120.0

In [23]:
df.fillna(999)   # simple version of filling in values instead of NaN -- give a scalar value

       x      y      z
a  999.0   20.0  999.0
b   40.0  999.0   60.0
c   70.0   80.0   90.0
d  100.0  999.0  120.0

In [24]:
df.dtypes

x    float64
y    float64
z    float64
dtype: object

In [25]:
# it's very common to use fillna with the mean of each column
# we can do that by invoking mean, which will give a series
# then we can pass that series to fillna, and each column will be fillna'd with its own mean

df.mean()

x    70.0
y    50.0
z    90.0
dtype: float64

In [27]:
df

       x     y      z
a    NaN  20.0    NaN
b   40.0   NaN   60.0
c   70.0  80.0   90.0
d  100.0   NaN  120.0

In [28]:
df.fillna(df.mean())

       x     y      z
a   70.0  20.0   90.0
b   40.0  50.0   60.0
c   70.0  80.0   90.0
d  100.0  50.0  120.0

In [29]:
df.interpolate()

       x     y      z
a    NaN  20.0    NaN
b   40.0  50.0   60.0
c   70.0  80.0   90.0
d  100.0  80.0  120.0

In [30]:
help(df.interpolate)

Help on method interpolate in module pandas.core.generic:

interpolate(
    method: InterpolateOptions = 'linear',
    *,
    axis: Axis = 0,
    limit: int | None = None,
    inplace: bool = False,
    limit_direction: Literal['forward', 'backward', 'both'] | None = None,
    limit_area: Literal['inside', 'outside'] | None = None,
    **kwargs
) -> Self method of pandas.DataFrame instance
    Fill NaN values using an interpolation method.

    Please note that only ``method='linear'`` is supported for
    DataFrame/Series with a MultiIndex.

    Parameters
    ----------
    method : str, default 'linear'
        Interpolation technique to use. One of:

        * 'linear': Ignore the index and treat the values as equally
          spaced. This is the only method supported on MultiIndexes.
        * 'time': Works on daily and higher resolution data to interpolate
          given length of interval. This interpolates values based on
          time interval between observations.
        * 'index': The interpolation uses the numerical values
          of the DataFrame's index to linearly calculate missing values.
        * 'values': Interpolation based on the numerical values
          in the DataFrame, treating them as equally spaced along the index.
        * 'nearest', 'zero', 'slinear', 'quadratic', 'cubic',
          'barycentric', 'polynomial': Passed to
          `scipy.interpolate.interp1d`, whereas 'spline' is passed to
          `scipy.interpolate.UnivariateSpline`. These methods use the numerical
          values of the index.  Both 'polynomial' and 'spline' require that
          you also specify an `order` (int), e.g.
          ``df.interpolate(method='polynomial', order=5)``. Note that,
          `slinear` method in Pandas refers to the Scipy first order `spline`
          instead of Pandas first order `spline`.
        * 'krogh', 'piecewise_polynomial', 'spline', 'pchip', 'akima',
          'cubicspline': Wrappers around the SciPy interpolation methods of
          similar names. See `Notes`.
        * 'from_derivatives': Refers to
          `scipy.interpolate.BPoly.from_derivatives`.

    axis : {0 or 'index', 1 or 'columns', None}, default None
        Axis to interpolate along. For `Series` this parameter is unused
        and defaults to 0.
    limit : int, optional
        Maximum number of consecutive NaNs to fill. Must be greater than
        0.
    inplace : bool, default False
        Update the data in place if possible.
    limit_direction : {'forward', 'backward', 'both'}, optional, default 'forward'
        Consecutive NaNs will be filled in this direction.

    limit_area : {`None`, 'inside', 'outside'}, default None
        If limit is specified, consecutive NaNs will be filled with this
        restriction.

        * ``None``: No fill restriction.
        * 'inside': Only fill NaNs surrounded by valid values
          (interpolate).
        * 'outside': Only fill NaNs outside valid values (extrapolate).

    **kwargs : optional
        Keyword arguments to pass on to the interpolating function.

    Returns
    -------
    Series or DataFrame
        Returns the same object type as the caller, interpolated at
        some or all ``NaN`` values.

    See Also
    --------
    fillna : Fill missing values using different methods.
    scipy.interpolate.Akima1DInterpolator : Piecewise cubic polynomials
        (Akima interpolator).
    scipy.interpolate.BPoly.from_derivatives : Piecewise polynomial in the
        Bernstein basis.
    scipy.interpolate.interp1d : Interpolate a 1-D function.
    scipy.interpolate.KroghInterpolator : Interpolate polynomial (Krogh
        interpolator).
    scipy.interpolate.PchipInterpolator : PCHIP 1-d monotonic cubic
        interpolation.
    scipy.interpolate.CubicSpline : Cubic spline data interpolator.

    Notes
    -----
    The 'krogh', 'piecewise_polynomial', 'spline', 'pchip' and 'akima'
    methods are wrappers around the respective SciPy implementations of
    similar names. These use the actual numerical values of the index.
    For more information on their behavior, see the
    `SciPy documentation
    <https://docs.scipy.org/doc/scipy/reference/interpolate.html#univariate-interpolation>`__.

    Examples
    --------
    Filling in ``NaN`` in a :class:`~pandas.Series` via linear
    interpolation.

    >>> s = pd.Series([0, 1, np.nan, 3])
    >>> s
    0    0.0
    1    1.0
    2    NaN
    3    3.0
    dtype: float64
    >>> s.interpolate()
    0    0.0
    1    1.0
    2    2.0
    3    3.0
    dtype: float64

    Filling in ``NaN`` in a Series via polynomial interpolation or splines:
    Both 'polynomial' and 'spline' methods require that you also specify
    an ``order`` (int).

    >>> s = pd.Series([0, 2, np.nan, 8])
    >>> s.interpolate(method="polynomial", order=2)
    0    0.000000
    1    2.000000
    2    4.666667
    3    8.000000
    dtype: float64

    Fill the DataFrame forward (that is, going down) along each column
    using linear interpolation.

    Note how the last entry in column 'a' is interpolated differently,
    because there is no entry after it to use for interpolation.
    Note how the first entry in column 'b' remains ``NaN``, because there
    is no entry before it to use for interpolation.

    >>> df = pd.DataFrame(
    ...     [
    ...         (0.0, np.nan, -1.0, 1.0),
    ...         (np.nan, 2.0, np.nan, np.nan),
    ...         (2.0, 3.0, np.nan, 9.0),
    ...         (np.nan, 4.0, -4.0, 16.0),
    ...     ],
    ...     columns=list("abcd"),
    ... )
    >>> df
         a    b    c     d
    0  0.0  NaN -1.0   1.0
    1  NaN  2.0  NaN   NaN
    2  2.0  3.0  NaN   9.0
    3  NaN  4.0 -4.0  16.0
    >>> df.interpolate(method="linear", limit_direction="forward", axis=0)
         a    b    c     d
    0  0.0  NaN -1.0   1.0
    1  1.0  2.0 -2.0   5.0
    2  2.0  3.0 -3.0   9.0
    3  2.0  4.0 -4.0  16.0

    Using polynomial interpolation.

    >>> df["d"].interpolate(method="polynomial", order=2)
    0     1.0
    1     4.0
    2     9.0
    3    16.0
    Name: d, dtype: float64

# Adding columns

Very often, you'll want to add one or more columns to a data frame. Sometimes, it's for helpful temp storing of data while you're doing a complex set of calculations. Sometimes, you actually want to keep it around.

In either case, you can add a new column to a data frame by just assigning to it.

In [31]:
df

       x     y      z
a    NaN  20.0    NaN
b   40.0   NaN   60.0
c   70.0  80.0   90.0
d  100.0   NaN  120.0

In [32]:
df['t'] = 'hello to everyone today'.split()  # it must have 4 elements, otherwise assignment won't work

In [33]:
df['t']

a       hello
b          to
c    everyone
d       today
Name: t, dtype: str

In [34]:
df

       x     y      z         t
a    NaN  20.0    NaN     hello
b   40.0   NaN   60.0        to
c   70.0  80.0   90.0  everyone
d  100.0   NaN  120.0     today

In [36]:
df['product'] = df['x'] * df['z']
df['product']

a        NaN
b     2400.0
c     6300.0
d    12000.0
Name: product, dtype: float64

In [37]:
df

       x     y      z         t  product
a    NaN  20.0    NaN     hello      NaN
b   40.0   NaN   60.0        to   2400.0
c   70.0  80.0   90.0  everyone   6300.0
d  100.0   NaN  120.0     today  12000.0

# Setting and resetting the index

We've seen that retrieving values via the index is everywhere in Pandas. Sometimes, you'll want to set one of the "regular" columns to be the index. Or you'll want to "demote" a column from the index to be regular again.

- To make a column the index, use the `set_index` method. You have to provide a string, the name of the column.
- To remove a column from the index, turning it back into a regular column, use the `reset_index` method.

In [38]:
df

       x     y      z         t  product
a    NaN  20.0    NaN     hello      NaN
b   40.0   NaN   60.0        to   2400.0
c   70.0  80.0   90.0  everyone   6300.0
d  100.0   NaN  120.0     today  12000.0

In [40]:
df.reset_index()  # this returns a new data frame, and does not change df!

  index      x     y      z         t  product
0     a    NaN  20.0    NaN     hello      NaN
1     b   40.0   NaN   60.0        to   2400.0
2     c   70.0  80.0   90.0  everyone   6300.0
3     d  100.0   NaN  120.0     today  12000.0

In [41]:
df

       x     y      z         t  product
a    NaN  20.0    NaN     hello      NaN
b   40.0   NaN   60.0        to   2400.0
c   70.0  80.0   90.0  everyone   6300.0
d  100.0   NaN  120.0     today  12000.0

In [42]:
df.set_index('t')

              x     y      z  product
t
hello       NaN  20.0    NaN      NaN
to         40.0   NaN   60.0   2400.0
everyone   70.0  80.0   90.0   6300.0
today     100.0   NaN  120.0  12000.0

# Exercise: Groceries

1. Define/redefine a data frame with groceries. There should be three columns -- product, price, and department.
2. Set the index to be the product names.
3. Retrieve three items via the index, and find their min and max prices.
4. Set the index now to be the department. Find the mean price for items in any one department.

https://practice.lernerpython.com/classroom/ce06963a8d/ex-57

In [43]:
df = DataFrame([['apple', 5, 'produce'],
                ['bananas', 3, 'produce'],
                ['computer', 500, 'electronics'],
                ['diary', 20, 'books'],
                ['elephant', 100, 'pets']],
               index=[123, 124, 345, 456, 789],
               columns='product price department'.split())

df

      product  price   department
123     apple      5      produce
124   bananas      3      produce
345  computer    500  electronics
456     diary     20        books
789  elephant    100         pets

In [44]:
df.set_index('product')

          price   department
product
apple         5      produce
bananas       3      produce
computer    500  electronics
diary        20        books
elephant    100         pets

In [52]:
# method chaining

(
    df
    .set_index('product')
    .loc[ ['apple', 'computer', 'elephant'] ]   # fancy indexing
    .agg(['min', 'max'])
)

     price   department
min      5  electronics
max    500      produce

In [56]:
(
    df
    .set_index('department')
    .loc['produce']
    ['price']
    .mean()
)

np.float64(4.0)

# Exercise: Adding/modifying columns

1. Use the grocery store data frame.
2. Add a new column, `tax`, the percentage tax applied to each item. Vary according to the department.
3. Add a new column, `total_price`, which is the price + (price * tax).
4. Retrieve products where total_price is > 50.

https://practice.lernerpython.com/classroom/ce06963a8d/ex-58

In [57]:
df

      product  price   department
123     apple      5      produce
124   bananas      3      produce
345  computer    500  electronics
456     diary     20        books
789  elephant    100         pets

In [58]:
df['tax'] = 1.00  # this will be assigned to all rows

df

      product  price   department  tax
123     apple      5      produce  1.0
124   bananas      3      produce  1.0
345  computer    500  electronics  1.0
456     diary     20        books  1.0
789  elephant    100         pets  1.0

In [59]:
df['tax'] = [0.05, .05, .1, .01, 1.0]

df

      product  price   department   tax
123     apple      5      produce  0.05
124   bananas      3      produce  0.05
345  computer    500  electronics  0.10
456     diary     20        books  0.01
789  elephant    100         pets  1.00

In [61]:
# calculate and add to our data frame
df['total_price'] = df['price'] * df['tax']

In [62]:
df

      product  price   department   tax  total_price
123     apple      5      produce  0.05         0.25
124   bananas      3      produce  0.05         0.15
345  computer    500  electronics  0.10        50.00
456     diary     20        books  0.01         0.20
789  elephant    100         pets  1.00       100.00

In [64]:
(
    df
    .loc[ df['total_price'] >= 50 ]
)

      product  price   department  tax  total_price
345  computer    500  electronics  0.1         50.0
789  elephant    100         pets  1.0        100.0

# Loading real-world data! 

When I started to work with data, I was sure I would be using some binary file format that was really smart about assigning dtypes and moving them between the file and Pandas.

I was wrong -- we normally use CSV (comma-separated values, a text format) or Excel (mostly textual, but with some binary aspects) when we read data. There are some binary formats, especially Parquet (which is newish, and part of the PyArrow world), but mostly we work with CSV.

Normally, or in the simple case, a CSV file is:
- One record per line
- Fields in a record are separated with commas
- The first row in the file contains the headers, which will be used as the column names in our data frame
- Pandas examines the data in each column, and assigns a dtype:
    - If there are only digits, it assigns `int64`
    - If there are digits and a decimal point, it assigns `float64`
    - In all other cases, it treats the column as strings -- in Pandas 2, it'll be `object` and in Pandas 3, it'll be `str`.

To read a CSV file into Pandas:
1. Use the `pd.read_csv` method -- not `df.read_csv`, because we're creating a new data frame based on the file's contents.
2. We can pass the filename, and a number of other possible arguments.
3. The result, returned to us, is a new data frame.

In [66]:
filename = 'taxi.csv'
df = pd.read_csv(filename)  

df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,2,2015-06-02 11:19:29,2015-06-02 11:47:52,1,1.63,-73.954430,40.764141,1,N,-73.974754,40.754093,2,17.0,0.0,0.5,0.00,0.0,0.3,17.80
1,2,2015-06-02 11:19:30,2015-06-02 11:27:56,1,0.46,-73.971443,40.758942,1,N,-73.978539,40.761909,1,6.5,0.0,0.5,1.00,0.0,0.3,8.30
2,2,2015-06-02 11:19:31,2015-06-02 11:30:30,1,0.87,-73.978111,40.738434,1,N,-73.990273,40.745438,1,8.0,0.0,0.5,2.20,0.0,0.3,11.00
3,2,2015-06-02 11:19:31,2015-06-02 11:39:02,1,2.13,-73.945892,40.773529,1,N,-73.971527,40.760330,1,13.5,0.0,0.5,2.86,0.0,0.3,17.16
4,1,2015-06-02 11:19:32,2015-06-02 11:32:49,1,1.40,-73.979088,40.776772,1,N,-73.982162,40.758999,2,9.5,0.0,0.5,0.00,0.0,0.3,10.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,1,2015-06-01 00:12:59,2015-06-01 00:24:18,1,2.70,-73.947792,40.814972,1,N,-73.973358,40.783638,2,11.0,0.5,0.5,0.00,0.0,0.3,12.30
9995,1,2015-06-01 00:12:59,2015-06-01 00:28:16,1,4.50,-74.004066,40.747818,1,N,-73.953758,40.779285,1,16.0,0.5,0.5,3.00,0.0,0.3,20.30
9996,2,2015-06-01 00:13:00,2015-06-01 00:37:25,1,5.59,-73.994377,40.766102,1,N,-73.903206,40.750546,2,21.0,0.5,0.5,0.00,0.0,0.3,22.30
9997,2,2015-06-01 00:13:02,2015-06-01 00:19:10,6,1.54,-73.978302,40.748531,1,N,-73.989166,40.762852,2,6.5,0.5,0.5,0.00,0.0,0.3,7.80
9998,1,2015-06-01 00:13:04,2015-06-01 00:36:33,1,5.80,-73.983215,40.726414,1,N,-73.924133,40.701645,1,21.0,0.5,0.5,4.45,0.0,0.3,26.75

In [67]:
# how many parameters does read_csv support?

help(pd.read_csv)

Help on function read_csv in module pandas:

read_csv(
    filepath_or_buffer: FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str],
    *,
    sep: str | None | lib.NoDefault = <no_default>,
    delimiter: str | None | lib.NoDefault = None,
    header: int | Sequence[int] | None | Literal['infer'] = 'infer',
    names: Sequence[Hashable] | None | lib.NoDefault = <no_default>,
    index_col: IndexLabel | Literal[False] | None = None,
    usecols: UsecolsArgType = None,
    dtype: DtypeArg | None = None,
    engine: CSVEngine | None = None,
    converters: Mapping[HashableT, Callable] | None = None,
    true_values: list | None = None,
    false_values: list | None = None,
    skipinitialspace: bool = False,
    skiprows: list[int] | int | Callable[[Hashable], bool] | None = None,
    skipfooter: int = 0,
    nrows: int | None = None,
    na_values: Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None = None,
    keep_default_na: bool = True,
    na_filter: bool = True,
    skip_blank_lines: bool = True,
    parse_dates: bool | Sequence[Hashable] | None = None,
    date_format: str | dict[Hashable, str] | None = None,
    dayfirst: bool = False,
    cache_dates: bool = True,
    iterator: bool = False,
    chunksize: int | None = None,
    compression: CompressionOptions = 'infer',
    thousands: str | None = None,
    decimal: str = '.',
    lineterminator: str | None = None,
    quotechar: str = '"',
    quoting: int = 0,
    doublequote: bool = True,
    escapechar: str | None = None,
    comment: str | None = None,
    encoding: str | None = None,
    encoding_errors: str | None = 'strict',
    dialect: str | csv.Dialect | None = None,
    on_bad_lines: str = 'error',
    low_memory: bool = True,
    memory_map: bool = False,
    float_precision: Literal['high', 'legacy', 'round_trip'] | None = None,
    storage_options: StorageOptions | None = None,
    dtype_backend: DtypeBackend | lib.NoDefault = <no_default>
) -> DataFrame | TextFileReader
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names:
        if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.

        When inferred from the file contents, headers are kept distinct from
        each other by renaming duplicate names with a numeric suffix of the form
        ``".{count}"`` starting from 1, e.g. ``"foo"`` and ``"foo.1"``.
        Empty headers are named ``"Unnamed: {i}"`` or ``
        "Unnamed: {i}_level_{level}"``
        in the case of MultiIndex columns.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
        Column(s) to use as row label(s), denoted either by column labels or column
        indices.  If a sequence of labels or indices is given,
        :class:`~pandas.MultiIndex`
        will be formed for the row labels.

        Note: ``index_col=False`` can be used to force pandas to *not* use the first
        column as the index, e.g., when you have a malformed file with delimiters at
        the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either
        by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s).
        If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {Hashable : dtype}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion. Specify a ``defaultdict`` as input where
        the default determines the ``dtype``
        of the columns which are not explicitly
        listed.
    engine : {'c', 'python', 'pyarrow'}, optional
        Parser engine to use. The C and pyarrow engines are faster,
        while the python engine
        is currently more feature-complete. Multithreading
        is currently only supported by
        the pyarrow engine. Some features of the "pyarrow" engine
        are unsupported or may not work correctly.
    converters : dict of {Hashable : Callable}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition
        to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive
        variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False``
        otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
        Refers to the number of data rows in the returned DataFrame, excluding:

        * The header row containing column names.
        * Rows before the header row, if ``header=1`` or larger.

        Example usage:

        * To read the first 999,999 (non-header) rows:
          ``read_csv(..., nrows=999999)``

        * To read rows 1,000,000 through 1,999,999:
          ``read_csv(..., skiprows=1000000, nrows=999999)``

    na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable},
        optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict``
        passed, specific
        per-column ``NA`` values.  By default the following values
        are interpreted as
        ``NaN``: empty string, "NaN", "N/A", "NULL", and other common
        representations of missing data.
    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values``
          are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``,
        the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, None, list of Hashable, default None
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index.
        * ``None``. Behaves like ``True`` if ``date_format`` is specified.
        * ``list`` of ``int`` or names.
          e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates and/or times when
        used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"`` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
          time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
          and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data.
        If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only
        one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``,
        ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for
        Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL,
        2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that
        only fields containing special
        characters are quoted (e.g., characters defined
        in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
        When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
        whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
        field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are:

        - ``'error'``, raise an Exception when a bad line is encountered.
        - ``'warn'``, raise a warning when a bad line is
          encountered and skip that line.
        - ``'skip'``, skip bad lines without raising or warning when
          they are encountered.
        - Callable, function that will process a single bad line.
            - With ``engine='python'``, function with signature
              ``(bad_line: list[str]) -> list[str] | None``.
              ``bad_line`` is a list of strings split by the ``sep``.
              If the function returns ``None``, the bad line will be ignored.
              If the function returns a new ``list`` of strings with
              more elements than
              expected, a ``ParserWarning`` will be emitted while
              dropping extra elements.
            - With ``engine='pyarrow'``, function with signature
              as described in pyarrow documentation: `invalid_row_handler
              <https://arrow.apache.org/docs/python
              /generated/pyarrow.csv.ParseOptions.html
              #pyarrow.csv.ParseOptions.invalid_row_handler>`_.

        .. versionchanged:: 2.2.0

            Callable for ``engine='pyarrow'``

    low_memory : bool, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set ``False``, or specify the type with the ``dtype`` parameter.
        Note that the entire file is read into a single :class:`~pandas.DataFrame`
        regardless, use the ``chunksize`` or ``iterator``
        parameter to return the data in
        chunks. (Only valid with C parser).
    memory_map : bool, default False
        If a filepath is provided for ``filepath_or_buffer``, map the file object
        directly onto memory and access the data directly from there. Using this
        option can improve performance because there is no longer any I/O overhead.

# I've got the data. How do we work with it?

Our favorite tool to retrieve selected parts of the data is to use `.loc`.

We can use `.loc` on a data frame with either one argument (selecting the rows) or with two arguments (selecting the rows, and then selecting the columns):

- `.loc` with one argument, it can be
    - a single index
    - a list of indexes
    - a slice
    - a boolean series
- when `.loc` has two arguments, the second is the column selector:
    - a single column name
    - a list of columns names
    - (very rarely) a boolean series for selective retrieval

In [76]:
# I want the mean total_price for all rides where trip_distance was > 20.

(
    df
    .loc[
            pd.col('trip_distance') > 20    # row selector
              ,
            'total_amount'                   # column selector
        ]
    .mean()
)

np.float64(82.8916)

# Exercise: Weird taxi rides

1. Read `taxi.csv` into a data frame. This contains 9,999 taxi rides + one header row.
2. How many rides went 0 miles (`trip_distance`)? How much, on average, did people pay (`total_amount`) for such rides?
3. How many rides cost <= 0 dollars? (`total_amount`) How far (`trip_distance`), on average, did people go on such trips?
4. How many rides had 0 `passenger_count`? What were the mean `trip_distance` and `total_amount` for those rides?

https://practice.lernerpython.com/classroom/ce06963a8d/ex-59

In [77]:
df = pd.read_csv('taxi.csv')

In [82]:
# How many rides went 0 miles (trip_distance)? How much, on average, did people pay (total_amount) for such rides?

(
    df
    .loc[ pd.col('trip_distance') == 0 ,  # row selector
          'total_amount' ]   # column selector
    .agg(['mean', 'count'])
)

mean     31.58194
count    67.00000
Name: total_amount, dtype: float64

In [ ]:
# How many rides cost <= 0 dollars? (total_amount) How far (trip_distance), on average, did people go on such trips?
# How many rides had 0 passenger_count? What were the mean trip_distance and total_amount for those rides?