# Agenda

1. Useful methods + attributes
2. `NaN` and data frames
3. Boolean indexes and data frames
4. Adding columns
5. (Finally!) Files

In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [2]:
df = DataFrame([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]],
               index=list('abcd'),
               columns=list('xyz'))
df

     x    y    z
a   10   20   30
b   40   50   60
c   70   80   90
d  100  110  120

In [3]:
# if I want the mean of a given column, I can grab that column and run mean

df['x'].mean()

np.float64(55.0)

In [4]:
# what happens if I invoke the mean method on the data frame, rather than one column?

df.mean()

x    55.0
y    65.0
z    75.0
dtype: float64

In [5]:
df['z'].max()

np.int64(120)

In [6]:
df.max()

x    100
y    110
z    120
dtype: int64

The general rule of thumb is that if you run a series method on a data frame, the method is run on each column, and you get a result for each column, labeled with the column's name.

However... if you want, you can often invoke the method passing the "axis" keyword argument. If you pass "axis='columns'", then it'll go the other way.

In [7]:
df

     x    y    z
a   10   20   30
b   40   50   60
c   70   80   90
d  100  110  120

In [8]:
df.max()

x    100
y    110
z    120
dtype: int64

In [10]:
df.max(axis='columns')

a     30
b     60
c     90
d    120
dtype: int64

In [11]:
df.max(axis=0)  # in NumPy, you have to say 0 or 1 for the axis, and 0 is the

x    100
y    110
z    120
dtype: int64

In [12]:
df.max(axis=1)

a     30
b     60
c     90
d    120
dtype: int64