# Agenda

1. Joins
2. Strings

# Joins

The basic idea behind joining is that you have two different data frames that share an index -- or that share values in an index -- and you want to combine these into a single data frame.

This is very common if you have a large data set that is broken up into multiple files. Typically, each file (i.e., data frame) will have a number of different columns. So a company might have one data set with employee names and personal information, and another one with salary information, and yet another with performance information. If we want to do some analysis that uses information from all three of these data sets, then we'll need (want) to combine them into a single Pandas data frame, and then we can perform our query.

Joining would mean that all three of these data frames share an index, or at least share an index's values. You join across the index(es), get a single, large (wide) data frame, and then perform your queries.

If you don't want to join on the index, but want to use a non-index column, then you can use what Pandas calls "merge." Merging is basically the same as joining, except that it can be done on any column.

You'll often find that you'll need to use `set_index` to move a column into the index (if you want to `join`), or `reset_index` to move a column *out* of the index (if you want to `merge`).

In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [6]:
oil_prices = DataFrame([[1, 60],
                        [2, 65],
                        [3, 63],
                        [4, 69],
                        [5, 72],
                        [6, 65],
                        [7, 60],
                        [8, 55],
                        [9, 60],
                        [10, 62],
                        [11, 63],
                        [12, 65]],
                      columns=['month', 'price'])
oil_prices

    month  price
0       1     60
1       2     65
2       3     63
3       4     69
4       5     72
5       6     65
6       7     60
7       8     55
8       9     60
9      10     62
10     11     63
11     12     65

In [7]:
# I want to know the (mean) price of oil, for each month... that is already in my oil_prices data frame, right?
# Except that I want to see the names of the months, not the numbers.

months = DataFrame([[1, 'January'],
                     [2, 'February'],
                     [3, 'March'],
                     [4, 'April'],
                     [5, 'May'],
                     [6, 'June'],
                     [7, 'July'],
                     [8, 'August'],
                     [9, 'September'],
                     [10, 'October'],
                    [11, 'November'],
                     [12, 'December']],
                  columns=['number', 'name'])

months

    number       name
0        1    January
1        2   February
2        3      March
3        4      April
4        5        May
5        6       June
6        7       July
7        8     August
8        9  September
9       10    October
10      11   November
11      12   December

In [8]:
oil_prices = oil_prices.set_index('month')
months = months.set_index('number')

In [9]:
oil_prices

       price
month
1         60
2         65
3         63
4         69
5         72
6         65
7         60
8         55
9         60
10        62
11        63
12        65

In [10]:
months

             name
number
1         January
2        February
3           March
4           April
5             May
6            June
7            July
8          August
9       September
10        October
11       November
12       December

In [11]:
# in this join,

# oil_prices is known as the "left side"
# and months is known as the "right side"

oil_prices.join(months)

       price       name
month
1         60    January
2         65   February
3         63      March
4         69      April
5         72        May
6         65       June
7         60       July
8         55     August
9         60  September
10        62    October
11        63   November
12        65   December

In [12]:
oil_prices = DataFrame([[1, 60],
                        [2, 65],
                        [3, 63],
                        [4, 69],
                        [5, 72],
                        [6, 65],
                        [7, 60],
                        [8, 55],
                        [9, 60],
                        [10, 62],
                        [11, 63],
                        [12, 65],

                        [1, 60],
                        [2, 65],
                        [3, 63],
                        [4, 69],
                        [5, 72],
                        [6, 65],
                        [7, 60],
                        [8, 55],
                        [9, 60],
                        [10, 62],
                        [11, 63],
                        [12, 65]
                       ],
                      columns=['month', 'price'])
oil_prices

    month  price
0       1     60
1       2     65
2       3     63
3       4     69
4       5     72
5       6     65
6       7     60
7       8     55
8       9     60
9      10     62
10     11     63
11     12     65
12      1     60
13      2     65
14      3     63
15      4     69
16      5     72
17      6     65
18      7     60
19      8     55
20      9     60
21     10     62
22     11     63
23     12     65

In [13]:
oil_prices = oil_prices.set_index('month')

In [14]:
# what will happen now? oil_prices has 24 elements, but months has only 12...
oil_prices.join(months)

       price       name
month
1         60    January
2         65   February
3         63      March
4         69      April
5         72        May
6         65       June
7         60       July
8         55     August
9         60  September
10        62    October
11        63   November
12        65   December
1         60    January
2         65   February
3         63      March
4         69      April
5         72        May
6         65       June
7         60       July
8         55     August
9         60  September
10        62    October
11        63   November
12        65   December

In [15]:
# let's add a weird instance of a 13th month

oil_prices = DataFrame([[1, 60],
                        [2, 65],
                        [3, 63],
                        [4, 69],
                        [5, 72],
                        [6, 65],
                        [7, 60],
                        [8, 55],
                        [9, 60],
                        [10, 62],
                        [11, 63],
                        [12, 65],
                        [13, 62],

                        [1, 60],
                        [2, 65],
                        [3, 63],
                        [4, 69],
                        [5, 72],
                        [6, 65],
                        [7, 60],
                        [8, 55],
                        [9, 60],
                        [10, 62],
                        [11, 63],
                        [12, 65]
                       ],
                      columns=['month', 'price'])
oil_prices

    month  price
0       1     60
1       2     65
2       3     63
3       4     69
4       5     72
5       6     65
6       7     60
7       8     55
8       9     60
9      10     62
10     11     63
11     12     65
12     13     62
13      1     60
14      2     65
15      3     63
16      4     69
17      5     72
18      6     65
19      7     60
20      8     55
21      9     60
22     10     62
23     11     63
24     12     65

In [16]:
oil_prices = oil_prices.set_index('month')

In [17]:
oil_prices.join(months)

       price       name
month
1         60    January
2         65   February
3         63      March
4         69      April
5         72        May
6         65       June
7         60       July
8         55     August
9         60  September
10        62    October
11        63   November
12        65   December
13        62        NaN
1         60    January
2         65   February
3         63      March
4         69      April
5         72        May
6         65       June
7         60       July
8         55     August
9         60  September
10        62    October
11        63   November
12        65   December

In [18]:
# what if we do it in the other direction?

months.join(oil_prices)

             name  price
number
1         January     60
1         January     60
2        February     65
2        February     65
3           March     63
3           March     63
4           April     69
4           April     69
5             May     72
5             May     72
6            June     65
6            June     65
7            July     60
7            July     60
8          August     55
8          August     55
9       September     60
9       September     60
10        October     62
10        October     62
11       November     63
11       November     63
12       December     65
12       December     65

When you invoke `join`, the index on the left-hand data frame determines what will be included. If your left hand side's index has more values than the right-hand side index, then you'll have NaN in your result. But if the left side is a subset of the right side, that won't happen.

# Exercise: Joining

1. Create a data frame with the names of people in your family, and their ages.
2. Create a second, separate data frame with the names and shoe sizes of people in your family.
3. Join these together, and find the mean age per shoe size.

https://practice.lernerpython.com/classroom/ce06963a8d/ex-65

In [20]:
ages = DataFrame([['Reuven', 56],
                  ['SF', 54],
                  ['AMLF', 25],
                  ['SBLF', 23],
                  ['ADLF', 20]],
                columns=['name', 'age'])

ages

     name  age
0  Reuven   56
1      SF   54
2    AMLF   25
3    SBLF   23
4    ADLF   20

In [21]:
shoe_sizes = DataFrame([['Reuven', 46],
                  ['SF', 40],
                  ['AMLF', 40],
                  ['SBLF', 40],
                  ['ADLF', 44]],
                columns=['name', 'shoe_size'])

shoe_sizes

     name  shoe_size
0  Reuven         46
1      SF         40
2    AMLF         40
3    SBLF         40
4    ADLF         44

In [25]:
(
    ages
    .set_index('name')
    .join(shoe_sizes
        .set_index('name'))
    .groupby('shoe_size')['age'].mean()
)

shoe_size
40    34.0
44    20.0
46    56.0
Name: age, dtype: float64

# What about `merge`?

The idea of `merge` is that you can join on any columns, not just on the index.

In [27]:
(
    ages
    .merge(shoe_sizes)
)

     name  age  shoe_size
0  Reuven   56         46
1      SF   54         40
2    AMLF   25         40
3    SBLF   23         40
4    ADLF   20         44

In [28]:
help(ages.merge)

Help on method merge in module pandas.core.frame:

merge(
    right: DataFrame | Series,
    how: MergeHow = 'inner',
    on: IndexLabel | AnyArrayLike | None = None,
    left_on: IndexLabel | AnyArrayLike | None = None,
    right_on: IndexLabel | AnyArrayLike | None = None,
    left_index: bool = False,
    right_index: bool = False,
    sort: bool = False,
    suffixes: Suffixes = ('_x', '_y'),
    copy: bool | lib.NoDefault = <no_default>,
    indicator: str | bool = False,
    validate: MergeValidate | None = None
) -> DataFrame method of pandas.DataFrame instance
    Merge DataFrame or named Series objects with a database-style join.

    A named Series object is treated as a DataFrame with a single named column.

    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    When performing a cross merge, no column specifications to merge on are
    allowed.

    .. warning::

        If both key columns contain rows where the key is a null value, those
        rows will be matched against each other. This is different from usual SQL
        join behaviour and can lead to unexpected results.

    Parameters
    ----------
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner', 'cross', 'left_anti', 'right_anti'},
        default 'inner'
        Type of merge to be performed.

        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key order.
        * outer: use union of keys from both frames, similar to a SQL full outer
          join; sort keys lexicographically.
        * inner: use intersection of keys from both frames, similar to a SQL inner
          join; preserve the order of the left keys.
        * cross: creates the cartesian product from both frames, preserves the order
          of the left keys.
        * left_anti: use only keys from left frame that are not in right frame, similar
          to SQL left anti join; preserve key order.

          .. versionadded:: 3.0
        * right_anti: use only keys from right frame that are not in left frame, similar
          to SQL right anti join; preserve key order.

          .. versionadded:: 3.0
    on : Hashable or a sequence of the previous
        Column or index level names to join on. These must be found in both
        DataFrames. If `on` is None and not merging on indexes then this defaults
        to the intersection of the columns in both DataFrames.
    left_on : Hashable or a sequence of the previous, or array-like
        Column or index level names to join on in the left DataFrame. Can also
        be an array or list of arrays of the length of the left DataFrame.
        These arrays are treated as if they are columns.
    right_on : Hashable or a sequence of the previous, or array-like
        Column or index level names to join on in the right DataFrame. Can also
        be an array or list of arrays of the length of the right DataFrame.
        These arrays are treated as if they are columns.
    left_index : bool, default False
        Use the index from the left DataFrame as the join key(s). If it is a
        MultiIndex, the number of keys in the other DataFrame (either the index
        or a number of columns) must match the number of levels.
    right_index : bool, default False
        Use the index from the right DataFrame as the join key. Same caveats as
        left_index.
    sort : bool, default False
        Sort the join keys lexicographically in the result DataFrame. If False,
        the order of the join keys depends on the join type (how keyword).
    suffixes : list-like, default is ("_x", "_y")
        A length-2 sequence where each element is optionally a string
        indicating the suffix to add to overlapping column names in
        `left` and `right` respectively. Pass a value of `None` instead
        of a string to indicate that the column name from `left` or
        `right` should be left as-is, with no suffix. At least one of the
        values must not be None.
    copy : bool, default False
        This keyword is now ignored; changing its value will have no
        impact on the method.

        .. deprecated:: 3.0.0

            This keyword is ignored and will be removed in pandas 4.0. Since
            pandas 3.0, this method always returns a new object using a lazy
            copy mechanism that defers copies until necessary
            (Copy-on-Write). See the `user guide on Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            for more details.

    indicator : bool or str, default False
        If True, adds a column to the output DataFrame called "_merge" with
        information on the source of each row. The column can be given a different
        name by providing a string argument. The column will have a Categorical
        type with the value of "left_only" for observations whose merge key only
        appears in the left DataFrame, "right_only" for observations
        whose merge key only appears in the right DataFrame, and "both"
        if the observation's merge key is found in both DataFrames.

    validate : str, optional
        If specified, checks if merge is of specified type.

        * "one_to_one" or "1:1": check if merge keys are unique in both
          left and right datasets.
        * "one_to_many" or "1:m": check if merge keys are unique in left
          dataset.
        * "many_to_one" or "m:1": check if merge keys are unique in right
          dataset.
        * "many_to_many" or "m:m": allowed, but does not result in checks.

    Returns
    -------
    DataFrame
        A DataFrame of the two merged objects.

    See Also
    --------
    merge_ordered : Merge with optional filling/interpolation.
    merge_asof : Merge on nearest keys.
    DataFrame.join : Similar method using indices.

    Examples
    --------
    >>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [1, 2, 3, 5]})
    >>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [5, 6, 7, 8]})
    >>> df1
        lkey value
    0   foo      1
    1   bar      2
    2   baz      3
    3   foo      5
    >>> df2
        rkey value
    0   foo      5
    1   bar      6
    2   baz      7
    3   foo      8

    Merge df1 and df2 on the lkey and rkey columns. The value columns have
    the default suffixes, _x and _y, appended.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey')
      lkey  value_x rkey  value_y
    0  foo        1  foo        5
    1  foo        1  foo        8
    2  bar        2  bar        6
    3  baz        3  baz        7
    4  foo        5  foo        5
    5  foo        5  foo        8

    Merge DataFrames df1 and df2 with specified left and right suffixes
    appended to any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey',
    ...           suffixes=('_left', '_right'))
      lkey  value_left rkey  value_right
    0  foo           1  foo            5
    1  foo           1  foo            8
    2  bar           2  bar            6
    3  baz           3  baz            7
    4  foo           5  foo            5
    5  foo           5  foo            8

    Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
    any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
    Traceback (most recent call last):
    ...
    ValueError: columns overlap but no suffix specified:
        Index(['value'], dtype='object')

    >>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
    >>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
    >>> df1
          a  b
    0   foo  1
    1   bar  2
    >>> df2
          a  c
    0   foo  3
    1   baz  4

    >>> df1.merge(df2, how='inner', on='a')
          a  b  c
    0   foo  1  3

    >>> df1.merge(df2, how='left', on='a')
          a  b  c
    0   foo  1  3.0
    1   bar  2  NaN

    >>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
    >>> df2 = pd.DataFrame({'right': [7, 8]})
    >>> df1
        left
    0   foo
    1   bar
    >>> df2
        right
    0   7
    1   8

    >>> df1.merge(df2, how='cross')
       left  right
    0   foo      7
    1   foo      8
    2   bar      7
    3   bar      8

In [29]:
ages.columns

Index(['name', 'age'], dtype='str')

In [30]:
shoe_sizes.columns

Index(['name', 'shoe_size'], dtype='str')

In [31]:
ages.columns.intersection(shoe_sizes.columns)

Index(['name'], dtype='str')

In [32]:
(
    ages
    .merge(shoe_sizes, on='name')   # make the join column explicit
)

     name  age  shoe_size
0  Reuven   56         46
1      SF   54         40
2    AMLF   25         40
3    SBLF   23         40
4    ADLF   20         44

# What if the names overlap?