# Agenda

1. Joins
2. Strings

# Joins

The basic idea behind joining is that you have two different data frames that share an index -- or that share values in an index -- and you want to combine these into a single data frame.

This is very common if you have a large data set that is broken up into multiple files. Typically, each file (i.e., data frame) will have a number of different columns. So a company might have one data set with employee names and personal information, and another one with salary information, and yet another with performance information. If we want to do some analysis that uses information from all three of these data sets, then we'll need (want) to combine them into a single Pandas data frame, and then we can perform our query.

Joining would mean that all three of these data frames share an index, or at least share an index's values. You join across the index(es), get a single, large (wide) data frame, and then perform your queries.

If you don't want to join on the index, but want to use a non-index column, then you can use what Pandas calls "merge." Merging is basically the same as joining, except that it can be done on any column.

You'll often find that you'll need to use `set_index` to move a column into the index (if you want to `join`), or `reset_index` to move a column *out* of the index (if you want to `merge`).

In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [6]:
oil_prices = DataFrame([[1, 60],
                        [2, 65],
                        [3, 63],
                        [4, 69],
                        [5, 72],
                        [6, 65],
                        [7, 60],
                        [8, 55],
                        [9, 60],
                        [10, 62],
                        [11, 63],
                        [12, 65]],
                      columns=['month', 'price'])
oil_prices

    month  price
0       1     60
1       2     65
2       3     63
3       4     69
4       5     72
5       6     65
6       7     60
7       8     55
8       9     60
9      10     62
10     11     63
11     12     65

In [7]:
# I want to know the (mean) price of oil, for each month... that is already in my oil_prices data frame, right?
# Except that I want to see the names of the months, not the numbers.

months = DataFrame([[1, 'January'],
                     [2, 'February'],
                     [3, 'March'],
                     [4, 'April'],
                     [5, 'May'],
                     [6, 'June'],
                     [7, 'July'],
                     [8, 'August'],
                     [9, 'September'],
                     [10, 'October'],
                    [11, 'November'],
                     [12, 'December']],
                  columns=['number', 'name'])

months

    number       name
0        1    January
1        2   February
2        3      March
3        4      April
4        5        May
5        6       June
6        7       July
7        8     August
8        9  September
9       10    October
10      11   November
11      12   December

In [8]:
oil_prices = oil_prices.set_index('month')
months = months.set_index('number')

In [9]:
oil_prices

       price
month
1         60
2         65
3         63
4         69
5         72
6         65
7         60
8         55
9         60
10        62
11        63
12        65

In [10]:
months

             name
number
1         January
2        February
3           March
4           April
5             May
6            June
7            July
8          August
9       September
10        October
11       November
12       December

In [11]:
# in this join,

# oil_prices is known as the "left side"
# and months is known as the "right side"

oil_prices.join(months)

       price       name
month
1         60    January
2         65   February
3         63      March
4         69      April
5         72        May
6         65       June
7         60       July
8         55     August
9         60  September
10        62    October
11        63   November
12        65   December

In [12]:
oil_prices = DataFrame([[1, 60],
                        [2, 65],
                        [3, 63],
                        [4, 69],
                        [5, 72],
                        [6, 65],
                        [7, 60],
                        [8, 55],
                        [9, 60],
                        [10, 62],
                        [11, 63],
                        [12, 65],

                        [1, 60],
                        [2, 65],
                        [3, 63],
                        [4, 69],
                        [5, 72],
                        [6, 65],
                        [7, 60],
                        [8, 55],
                        [9, 60],
                        [10, 62],
                        [11, 63],
                        [12, 65]
                       ],
                      columns=['month', 'price'])
oil_prices

    month  price
0       1     60
1       2     65
2       3     63
3       4     69
4       5     72
5       6     65
6       7     60
7       8     55
8       9     60
9      10     62
10     11     63
11     12     65
12      1     60
13      2     65
14      3     63
15      4     69
16      5     72
17      6     65
18      7     60
19      8     55
20      9     60
21     10     62
22     11     63
23     12     65

In [13]:
oil_prices = oil_prices.set_index('month')

In [14]:
# what will happen now? oil_prices has 24 elements, but months has only 12...
oil_prices.join(months)

       price       name
month
1         60    January
2         65   February
3         63      March
4         69      April
5         72        May
6         65       June
7         60       July
8         55     August
9         60  September
10        62    October
11        63   November
12        65   December
1         60    January
2         65   February
3         63      March
4         69      April
5         72        May
6         65       June
7         60       July
8         55     August
9         60  September
10        62    October
11        63   November
12        65   December

In [15]:
# let's add a weird instance of a 13th month

oil_prices = DataFrame([[1, 60],
                        [2, 65],
                        [3, 63],
                        [4, 69],
                        [5, 72],
                        [6, 65],
                        [7, 60],
                        [8, 55],
                        [9, 60],
                        [10, 62],
                        [11, 63],
                        [12, 65],
                        [13, 62],

                        [1, 60],
                        [2, 65],
                        [3, 63],
                        [4, 69],
                        [5, 72],
                        [6, 65],
                        [7, 60],
                        [8, 55],
                        [9, 60],
                        [10, 62],
                        [11, 63],
                        [12, 65]
                       ],
                      columns=['month', 'price'])
oil_prices

    month  price
0       1     60
1       2     65
2       3     63
3       4     69
4       5     72
5       6     65
6       7     60
7       8     55
8       9     60
9      10     62
10     11     63
11     12     65
12     13     62
13      1     60
14      2     65
15      3     63
16      4     69
17      5     72
18      6     65
19      7     60
20      8     55
21      9     60
22     10     62
23     11     63
24     12     65

In [16]:
oil_prices = oil_prices.set_index('month')

In [17]:
oil_prices.join(months)

       price       name
month
1         60    January
2         65   February
3         63      March
4         69      April
5         72        May
6         65       June
7         60       July
8         55     August
9         60  September
10        62    October
11        63   November
12        65   December
13        62        NaN
1         60    January
2         65   February
3         63      March
4         69      April
5         72        May
6         65       June
7         60       July
8         55     August
9         60  September
10        62    October
11        63   November
12        65   December

In [18]:
# what if we do it in the other direction?

months.join(oil_prices)

             name  price
number
1         January     60
1         January     60
2        February     65
2        February     65
3           March     63
3           March     63
4           April     69
4           April     69
5             May     72
5             May     72
6            June     65
6            June     65
7            July     60
7            July     60
8          August     55
8          August     55
9       September     60
9       September     60
10        October     62
10        October     62
11       November     63
11       November     63
12       December     65
12       December     65

When you invoke `join`, the index on the left-hand data frame determines what will be included. If your left hand side's index has more values than the right-hand side index, then you'll have NaN in your result. But if the left side is a subset of the right side, that won't happen.

# Exercise: Joining

1. Create a data frame with the names of people in your family, and their ages.
2. Create a second, separate data frame with the names and shoe sizes of people in your family.
3. Join these together, and find the mean age per shoe size.

https://practice.lernerpython.com/classroom/ce06963a8d/ex-65

In [20]:
ages = DataFrame([['Reuven', 56],
                  ['SF', 54],
                  ['AMLF', 25],
                  ['SBLF', 23],
                  ['ADLF', 20]],
                columns=['name', 'age'])

ages

     name  age
0  Reuven   56
1      SF   54
2    AMLF   25
3    SBLF   23
4    ADLF   20

In [21]:
shoe_sizes = DataFrame([['Reuven', 46],
                  ['SF', 40],
                  ['AMLF', 40],
                  ['SBLF', 40],
                  ['ADLF', 44]],
                columns=['name', 'shoe_size'])

shoe_sizes

     name  shoe_size
0  Reuven         46
1      SF         40
2    AMLF         40
3    SBLF         40
4    ADLF         44

In [25]:
(
    ages
    .set_index('name')
    .join(shoe_sizes
        .set_index('name'))
    .groupby('shoe_size')['age'].mean()
)

shoe_size
40    34.0
44    20.0
46    56.0
Name: age, dtype: float64

# What about `merge`?

The idea of `merge` is that you can join on any columns, not just on the index.

In [27]:
(
    ages
    .merge(shoe_sizes)
)

     name  age  shoe_size
0  Reuven   56         46
1      SF   54         40
2    AMLF   25         40
3    SBLF   23         40
4    ADLF   20         44

In [28]:
help(ages.merge)

Help on method merge in module pandas.core.frame:

merge(
    right: DataFrame | Series,
    how: MergeHow = 'inner',
    on: IndexLabel | AnyArrayLike | None = None,
    left_on: IndexLabel | AnyArrayLike | None = None,
    right_on: IndexLabel | AnyArrayLike | None = None,
    left_index: bool = False,
    right_index: bool = False,
    sort: bool = False,
    suffixes: Suffixes = ('_x', '_y'),
    copy: bool | lib.NoDefault = <no_default>,
    indicator: str | bool = False,
    validate: MergeValidate | None = None
) -> DataFrame method of pandas.DataFrame instance
    Merge DataFrame or named Series objects with a database-style join.

    A named Series object is treated as a DataFrame with a single named column.

    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    When performing a cross merge, no column specifications to merge on are
    allowed.

    .. warning::

        If both key columns contain rows where the key is a null value, those
        rows will be matched against each other. This is different from usual SQL
        join behaviour and can lead to unexpected results.

    Parameters
    ----------
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner', 'cross', 'left_anti', 'right_anti'},
        default 'inner'
        Type of merge to be performed.

        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key order.
        * outer: use union of keys from both frames, similar to a SQL full outer
          join; sort keys lexicographically.
        * inner: use intersection of keys from both frames, similar to a SQL inner
          join; preserve the order of the left keys.
        * cross: creates the cartesian product from both frames, preserves the order
          of the left keys.
        * left_anti: use only keys from left frame that are not in right frame, similar
          to SQL left anti join; preserve key order.

          .. versionadded:: 3.0
        * right_anti: use only keys from right frame that are not in left frame, similar
          to SQL right anti join; preserve key order.

          .. versionadded:: 3.0
    on : Hashable or a sequence of the previous
        Column or index level names to join on. These must be found in both
        DataFrames. If `on` is None and not merging on indexes then this defaults
        to the intersection of the columns in both DataFrames.
    left_on : Hashable or a sequence of the previous, or array-like
        Column or index level names to join on in the left DataFrame. Can also
        be an array or list of arrays of the length of the left DataFrame.
        These arrays are treated as if they are columns.
    right_on : Hashable or a sequence of the previous, or array-like
        Column or index level names to join on in the right DataFrame. Can also
        be an array or list of arrays of the length of the right DataFrame.
        These arrays are treated as if they are columns.
    left_index : bool, default False
        Use the index from the left DataFrame as the join key(s). If it is a
        MultiIndex, the number of keys in the other DataFrame (either the index
        or a number of columns) must match the number of levels.
    right_index : bool, default False
        Use the index from the right DataFrame as the join key. Same caveats as
        left_index.
    sort : bool, default False
        Sort the join keys lexicographically in the result DataFrame. If False,
        the order of the join keys depends on the join type (how keyword).
    suffixes : list-like, default is ("_x", "_y")
        A length-2 sequence where each element is optionally a string
        indicating the suffix to add to overlapping column names in
        `left` and `right` respectively. Pass a value of `None` instead
        of a string to indicate that the column name from `left` or
        `right` should be left as-is, with no suffix. At least one of the
        values must not be None.
    copy : bool, default False
        This keyword is now ignored; changing its value will have no
        impact on the method.

        .. deprecated:: 3.0.0

            This keyword is ignored and will be removed in pandas 4.0. Since
            pandas 3.0, this method always returns a new object using a lazy
            copy mechanism that defers copies until necessary
            (Copy-on-Write). See the `user guide on Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            for more details.

    indicator : bool or str, default False
        If True, adds a column to the output DataFrame called "_merge" with
        information on the source of each row. The column can be given a different
        name by providing a string argument. The column will have a Categorical
        type with the value of "left_only" for observations whose merge key only
        appears in the left DataFrame, "right_only" for observations
        whose merge key only appears in the right DataFrame, and "both"
        if the observation's merge key is found in both DataFrames.

    validate : str, optional
        If specified, checks if merge is of specified type.

        * "one_to_one" or "1:1": check if merge keys are unique in both
          left and right datasets.
        * "one_to_many" or "1:m": check if merge keys are unique in left
          dataset.
        * "many_to_one" or "m:1": check if merge keys are unique in right
          dataset.
        * "many_to_many" or "m:m": allowed, but does not result in checks.

    Returns
    -------
    DataFrame
        A DataFrame of the two merged objects.

    See Also
    --------
    merge_ordered : Merge with optional filling/interpolation.
    merge_asof : Merge on nearest keys.
    DataFrame.join : Similar method using indices.

    Examples
    --------
    >>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [1, 2, 3, 5]})
    >>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [5, 6, 7, 8]})
    >>> df1
        lkey value
    0   foo      1
    1   bar      2
    2   baz      3
    3   foo      5
    >>> df2
        rkey value
    0   foo      5
    1   bar      6
    2   baz      7
    3   foo      8

    Merge df1 and df2 on the lkey and rkey columns. The value columns have
    the default suffixes, _x and _y, appended.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey')
      lkey  value_x rkey  value_y
    0  foo        1  foo        5
    1  foo        1  foo        8
    2  bar        2  bar        6
    3  baz        3  baz        7
    4  foo        5  foo        5
    5  foo        5  foo        8

    Merge DataFrames df1 and df2 with specified left and right suffixes
    appended to any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey',
    ...           suffixes=('_left', '_right'))
      lkey  value_left rkey  value_right
    0  foo           1  foo            5
    1  foo           1  foo            8
    2  bar           2  bar            6
    3  baz           3  baz            7
    4  foo           5  foo            5
    5  foo           5  foo            8

    Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
    any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
    Traceback (most recent call last):
    ...
    ValueError: columns overlap but no suffix specified:
        Index(['value'], dtype='object')

    >>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
    >>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
    >>> df1
          a  b
    0   foo  1
    1   bar  2
    >>> df2
          a  c
    0   foo  3
    1   baz  4

    >>> df1.merge(df2, how='inner', on='a')
          a  b  c
    0   foo  1  3

    >>> df1.merge(df2, how='left', on='a')
          a  b  c
    0   foo  1  3.0
    1   bar  2  NaN

    >>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
    >>> df2 = pd.DataFrame({'right': [7, 8]})
    >>> df1
        left
    0   foo
    1   bar
    >>> df2
        right
    0   7
    1   8

    >>> df1.merge(df2, how='cross')
       left  right
    0   foo      7
    1   foo      8
    2   bar      7
    3   bar      8

In [29]:
ages.columns

Index(['name', 'age'], dtype='str')

In [30]:
shoe_sizes.columns

Index(['name', 'shoe_size'], dtype='str')

In [31]:
ages.columns.intersection(shoe_sizes.columns)

Index(['name'], dtype='str')

In [32]:
(
    ages
    .merge(shoe_sizes, on='name')   # make the join column explicit
)

     name  age  shoe_size
0  Reuven   56         46
1      SF   54         40
2    AMLF   25         40
3    SBLF   23         40
4    ADLF   20         44

# What if the names overlap?

Column names in a Pandas data frame must be unique. (Very different from the rows, where uniqueness isn't an issue at all!)

What happens if both of the data frames have one or more columns with the same name? By default, `merge` will add `_x` to the left and `_y` to the right. We can set those, if we want, with keyword arguments.

In [34]:
# Let's make the column names overlap

ages.columns = ['name', 'data']
shoe_sizes.columns = ['name', 'data']

In [36]:
ages.merge(shoe_sizes, on='name')

     name  data_x  data_y
0  Reuven      56      46
1      SF      54      40
2    AMLF      25      40
3    SBLF      23      40
4    ADLF      20      44

In [40]:
(
    ages
    .set_index('name')
    .join(shoe_sizes
        .set_index('name'), lsuffix='_age', rsuffix='_shoe_size')
)

        data_age  data_shoe_size
name
Reuven        56              46
SF            54              40
AMLF          25              40
SBLF          23              40
ADLF          20              44

In [39]:
help(ages.join)

Help on method join in module pandas.core.frame:

join(
    other: DataFrame | Series | Iterable[DataFrame | Series],
    on: IndexLabel | None = None,
    how: MergeHow = 'left',
    lsuffix: str = '',
    rsuffix: str = '',
    sort: bool = False,
    validate: JoinValidate | None = None
) -> DataFrame method of pandas.DataFrame instance
    Join columns of another DataFrame.

    Join columns with `other` DataFrame either on index or on a key
    column. Efficiently join multiple DataFrame objects by index at once by
    passing a list.

    Parameters
    ----------
    other : DataFrame, Series, or a list containing any combination of them
        Index should be similar to one of the columns in this one. If a
        Series is passed, its name attribute must be set, and that will be
        used as the column name in the resulting joined DataFrame.
    on : str, list of str, or array-like, optional
        Column or index level name(s) in the caller to join on the index
        in `other`, otherwise joins index-on-index. If multiple
        values given, the `other` DataFrame must have a MultiIndex. Can
        pass an array as the join key if it is not already contained in
        the calling DataFrame. Like an Excel VLOOKUP operation.
    how : {'left', 'right', 'outer', 'inner', 'cross', 'left_anti', 'right_anti'},
        default 'left'
        How to handle the operation of the two objects.

        * left: use calling frame's index (or column if on is specified)
        * right: use `other`'s index.
        * outer: form union of calling frame's index (or column if on is
          specified) with `other`'s index, and sort it lexicographically.
        * inner: form intersection of calling frame's index (or column if
          on is specified) with `other`'s index, preserving the order
          of the calling's one.
        * cross: creates the cartesian product from both frames, preserves the order
          of the left keys.
        * left_anti: use set difference of calling frame's index and `other`'s
          index.
        * right_anti: use set difference of `other`'s index and calling frame's
          index.
    lsuffix : str, default ''
        Suffix to use from left frame's overlapping columns.
    rsuffix : str, default ''
        Suffix to use from right frame's overlapping columns.
    sort : bool, default False
        Order result DataFrame lexicographically by the join key. If False,
        the order of the join key depends on the join type (how keyword).
    validate : str, optional
        If specified, checks if join is of specified type.

        * "one_to_one" or "1:1": check if join keys are unique in both left
          and right datasets.
        * "one_to_many" or "1:m": check if join keys are unique in left dataset.
        * "many_to_one" or "m:1": check if join keys are unique in right dataset.
        * "many_to_many" or "m:m": allowed, but does not result in checks.

    Returns
    -------
    DataFrame
        A dataframe containing columns from both the caller and `other`.

    See Also
    --------
    DataFrame.merge : For column(s)-on-column(s) operations.

    Notes
    -----
    Parameters `on`, `lsuffix`, and `rsuffix` are not supported when
    passing a list of `DataFrame` objects.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     {
    ...         "key": ["K0", "K1", "K2", "K3", "K4", "K5"],
    ...         "A": ["A0", "A1", "A2", "A3", "A4", "A5"],
    ...     }
    ... )

    >>> df
      key   A
    0  K0  A0
    1  K1  A1
    2  K2  A2
    3  K3  A3
    4  K4  A4
    5  K5  A5

    >>> other = pd.DataFrame({"key": ["K0", "K1", "K2"], "B": ["B0", "B1", "B2"]})

    >>> other
      key   B
    0  K0  B0
    1  K1  B1
    2  K2  B2

    Join DataFrames using their indexes.

    >>> df.join(other, lsuffix="_caller", rsuffix="_other")
      key_caller   A key_other    B
    0         K0  A0        K0   B0
    1         K1  A1        K1   B1
    2         K2  A2        K2   B2
    3         K3  A3       NaN  NaN
    4         K4  A4       NaN  NaN
    5         K5  A5       NaN  NaN

    If we want to join using the key columns, we need to set key to be
    the index in both `df` and `other`. The joined DataFrame will have
    key as its index.

    >>> df.set_index("key").join(other.set_index("key"))
          A    B
    key
    K0   A0   B0
    K1   A1   B1
    K2   A2   B2
    K3   A3  NaN
    K4   A4  NaN
    K5   A5  NaN

    Another option to join using the key columns is to use the `on`
    parameter. DataFrame.join always uses `other`'s index but we can use
    any column in `df`. This method preserves the original DataFrame's
    index in the result.

    >>> df.join(other.set_index("key"), on="key")
      key   A    B
    0  K0  A0   B0
    1  K1  A1   B1
    2  K2  A2   B2
    3  K3  A3  NaN
    4  K4  A4  NaN
    5  K5  A5  NaN

    Using non-unique key values shows how they are matched.

    >>> df = pd.DataFrame(
    ...     {
    ...         "key": ["K0", "K1", "K1", "K3", "K0", "K1"],
    ...         "A": ["A0", "A1", "A2", "A3", "A4", "A5"],
    ...     }
    ... )

    >>> df
      key   A
    0  K0  A0
    1  K1  A1
    2  K1  A2
    3  K3  A3
    4  K0  A4
    5  K1  A5

    >>> df.join(other.set_index("key"), on="key", validate="m:1")
      key   A    B
    0  K0  A0   B0
    1  K1  A1   B1
    2  K1  A2   B1
    3  K3  A3  NaN
    4  K0  A4   B0
    5  K1  A5   B1

# Strings

So far, we've thought of Pandas and data frames as mostly being useful for working with numbers. And that's true! But they also handle strings (textual data) very well.

NumPy, which is the underlying system for Pandas, is *terrible* when it comes to working with strings. From the beginning, Pandas ignored the NumPy implementation, and did its own thing for strings. That is: The dtype for strings in Pandas was, for a long time, "object". That meant that the value stored in NumPy/Pandas was a pointer (i.e., a memory address) in Python. We used a *Python* string, and referred to its location.

- The good news is that Python strings are super flexible and useful.
- The bad news is that Python strings are in Python memory, and are large. They take a long time to access, and they use lots of memory.

However... as of Pandas 3.0, we don't need to worry about this any more! Strings are now implemented using PyArrow, a new alternative back-end storage system that is *far* faster and slimmer. Now, the dtype looks like `str` (not `object`), and things work much faster.

In [41]:
s = Series('this is a fantastic example of a series'.split())
s

0         this
1           is
2            a
3    fantastic
4      example
5           of
6            a
7       series
dtype: str

In [42]:
# let's say that I want to find the lengths of the words in this series. How can I?

len(s)   # not really... this will give us the length of the series

8

In [43]:
# how can I run the "len" function on every value in our series?
# (remember, using a "for" loop is almost ways a serious mistake.)

# Pandas provides us with a special "accessor" object, ".str", that we can use on a series
# that .str accessor gives us access to lots of string methods... including len!

s.str.len()  # this is the fastest/best way to get the length of each string

0    4
1    2
2    1
3    9
4    7
5    2
6    1
7    6
dtype: int64

In [44]:
s.str.contains('e')   # this is similar to 'e' in (each value of) s

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7     True
dtype: bool

In [45]:
s.loc[ s.str.contains('e') ]    # this returns the words in s that contain e|

4    example
7     series
dtype: str

The "str" accessor handles several dozen different methods 

- All of Python's string methods
- Some operators that are now methods (e.g., "contains")
- Some other methods from other languages (e.g., R) that were thrown in for good measure
- Some of the methods have the same names as Python methods, but are more powerful -- often supporting regular expressions

In [47]:
# you can even use [] to retrieve a particular character!

s.str[0]  # first letter of each string!

0    t
1    i
2    a
3    f
4    e
5    o
6    a
7    s
dtype: str

In [48]:
s.str[:3]   # first 3 letters of each string

0    thi
1     is
2      a
3    fan
4    exa
5     of
6      a
7    ser
dtype: str

# Exercise: Number of digits

1. Read `taxi.csv` into a data frame. (We'll really only care about one column, `trip_distance`.)
2. Convert `trip_distance` into an integer column, dropping any fractional values.
3. Find the mean number of digits in the `trip_distance` column.

https://practice.lernerpython.com/classroom/ce06963a8d/ex-68

In [50]:
df = pd.read_csv('taxi.csv', usecols=['trip_distance'])
df

      trip_distance
0              1.63
1              0.46
2              0.87
3              2.13
4              1.40
...             ...
9994           2.70
9995           4.50
9996           5.59
9997           1.54
9998           5.80

[9999 rows x 1 columns]

In [56]:
(
    df
    ['trip_distance']
    .astype(int)    # turn those floats into integers -- truncate the fractional part
    .astype(str)    # turn the integers into strings
    .str.len()      # how many digits are in each string?
    .mean()         # how many digits are there, on average, in the trip_distance?
)

np.float64(1.0713071307130713)

In [57]:
df['trip_distance'].describe()

count    9999.000000
mean        3.158511
std         4.037516
min         0.000000
25%         1.000000
50%         1.700000
75%         3.300000
max        64.600000
Name: trip_distance, dtype: float64

In [58]:
!ls

__pycache__			BDTMSD-Python-2026-10-02.ipynb
airlines.dat			BDTMSD-Python-2026-10-06.ipynb
airports			burrito_current.csv
BDTMSD-Python-2026-07-21.ipynb	celebrity_deaths_2016.csv
BDTMSD-Python-2026-07-24.ipynb	greet.py
BDTMSD-Python-2026-07-28.ipynb	languages.csv
BDTMSD-Python-2026-07-31.ipynb	linux-etc-passwd.txt
BDTMSD-Python-2026-08-04.ipynb	macos-passwd.txt
BDTMSD-Python-2026-08-07.ipynb	menu.py
BDTMSD-Python-2026-08-11.ipynb	mini-access-log.txt
BDTMSD-Python-2026-08-14.ipynb	myconfig.txt
BDTMSD-Python-2026-08-18.ipynb	myfile.txt
BDTMSD-Python-2026-08-21.ipynb	mymod.py
BDTMSD-Python-2026-08-25.ipynb	nums.txt
BDTMSD-Python-2026-08-28.ipynb	passwd.txt
BDTMSD-Python-2026-09-01.ipynb	pyproject.toml
BDTMSD-Python-2026-09-04.ipynb	README.md
BDTMSD-Python-2026-09-08.ipynb	shoe-data.txt
BDTMSD-Python-2026-09-11.ipynb	taxi.csv
BDTMSD-Python-2026-09-15.ipynb	titanic3.csv
BDTMSD-Python-2026-09-18.ipynb	uv.lock
BDTMSD-Python-2026-09-25.ipynb	wcfile.txt
BDTMSD-Python-2026-09-29.ipynb

In [72]:
text = Series(
           open('alice-in-wonderland.txt')    # get a file object
           .read()                            # get a string with the file's contents
           .split()                           # get a list of strings, broken across whitespace
)

text

0             ﻿The
1          Project
2        Gutenberg
3            EBook
4               of
           ...
12758           to
12759         hear
12760        about
12761          new
12762      eBooks.
Length: 12763, dtype: str

In [73]:
text.head(20)

0            ﻿The
1         Project
2       Gutenberg
3           EBook
4              of
5           Alice
6              in
7     Wonderland,
8              by
9           Lewis
10        Carroll
11           This
12          eBook
13             is
14            for
15            the
16            use
17             of
18         anyone
19       anywhere
dtype: str

In [74]:
# what are the 10 most common words in Alice in Wonderland?

text.value_counts().head(10)

the     732
and     362
a       321
to      311
of      300
in      211
she     197
was     160
said    129
it      122
Name: count, dtype: int64

In [75]:
# what are the 10 most common words in Alice in Wonderland that have > 4 characters?

(
    text
    .loc[ text.str.len() > 4 ]   # keep only words with > 4 characters
    .value_counts()           # count how often each word appears
    .head(10)                 # keep the 10 most common
)

Alice           101
Project          78
little           56
Gutenberg-tm     53
about            39
Alice,           29
Alice.           27
electronic       27
which            24
could            23
Name: count, dtype: int64

In [68]:
s = '   abcd    '
s.strip()  # returns a new string, based on s, but without the leading/trailing whitespace

'abcd'

We can pass a string to `str.strip` as an argument. That string contains all of the characters we want to remove from the start and end of the string.

One particularly useful string for removing punctuation is ... `string.punctuation` in the Python standard library.

In [70]:
import string

s = '"Hello!!!!"'
s.strip(string.punctuation)

'Hello'

In [77]:
(
    text
    .loc[ text.str.len() > 4 ]   # keep only words with > 4 characters
    .str.strip(string.punctuation)  # apply str.strip, removing leading/trailing punctuation
    .value_counts()           # count how often each word appears
    .head(10)                 # keep the 10 most common
)

Alice           166
Project          83
little           58
Gutenberg-tm     55
about            40
herself          33
other            33
works            32
could            29
Rabbit           28
Name: count, dtype: int64

In [78]:
# let's add a call to str.lower, to force lowercase

(
    text
    .loc[ text.str.len() > 4 ]   # keep only words with > 4 characters
    .str.strip(string.punctuation)  # apply str.strip, removing leading/trailing punctuation
    .str.lower()
    .value_counts()           # count how often each word appears
    .head(10)                 # keep the 10 most common
)

alice           168
project          87
little           59
gutenberg-tm     56
about            41
other            34
herself          33
there            32
works            32
rabbit           31
Name: count, dtype: int64

In [79]:
text = 'hello out there. I am fine today. Today is a great day.'

s = Series(text.split('.'))
s

0          hello out there
1          I am fine today
2     Today is a great day
3
dtype: str

In [80]:
# what can I do if I want to analyze the words? Now I'm kind of stuck...
# I can use str.split!

(
    s
    .str.split()  # now the values in our series are Python lists!
)

0           [hello, out, there]
1          [I, am, fine, today]
2    [Today, is, a, great, day]
3                            []
dtype: object

In [82]:
# now, how can I work with individual words?
# the solution is the "explode" method, which takes each list element and makes it an element of the *series*


(
    s
    .str.split()  # now the values in our series are Python lists!
    .explode()
    .dropna()
)

0    hello
0      out
0    there
1        I
1       am
1     fine
1    today
2    Today
2       is
2        a
2    great
2      day
dtype: str

# Exercise: Wine words

1. Build a data frame from the file `winemag-150k-reviews.csv`. (You can get it in the practice system or at https://files.lerner.co.il/data-science-exercise-files.zip .) Each review describes the country and area of origin, the vineyard, and a full-text review
2. What are the 10 most common words containing 5 letters or more in the wine description? Turn words into lowercase, and remove all leading/trailing punctuation. Also, remove the words "flavors", "aromas", "finish", and "drink".

https://practice.lernerpython.com/classroom/ce06963a8d/ex-69

In [87]:
df = pd.read_csv('winemag-150k-reviews.csv', usecols=['description'])

In [88]:
df.shape

(150930, 1)

In [89]:
df.head()

                                         description
0  This tremendous 100% varietal wine hails from ...
1  Ripe aromas of fig, blackberry and cassis are ...
2  Mac Watson honors the memory of a wine once ma...
3  This spent 20 months in 30% new French oak, an...
4  This is the top wine from La Bégude, named aft...

In [100]:
s = df['description']

(
    s
    .str.split()
    .explode()
    .loc[ lambda s_: s_.str.len() > 4 ]
    .str.lower()
    .str.strip(string.punctuation)
    .loc[ lambda s_: ~s_.isin(['flavors', 'aromas', 'finish', 'drink']) ]
    .value_counts()
    .head(10)
)

description
fruit      56496
acidity    32603
tannins    32186
cherry     30685
palate     28945
wine       26122
black      24599
spice      22658
sweet      21284
notes      19606
Name: count, dtype: int64